<?php if (count($projects) > 0): ?>
    <ul style="margin: 0;padding: 0;">
        <?php foreach ($projects as $p): ?>
            <li style="list-style-type: none">
                <?php echo $this->projHelper()->getIcon($p); ?>
                <a href="<?php echo $this->url('project/action-id', array('action' => 'view', 'id' => $p['proj_id'])) ?>"><?php echo $p['proj_title']; ?></a>
            </li>
        <?php endforeach; ?>
    </ul>
<?php else: ?>
    <p><i>There is no project evolved from this idea!</i></p>
<?php endif; ?>