<?php if (count($ideaRef) > 0): ?>
    <ul style="margin: 0;padding: 0;">
        <?php foreach ($ideaRef as $ref): ?>
            <li style="list-style-type: none">
                <?php echo $this->ideaHelper()->getIcon($ref);?>
                <a href="<?php echo $this->url('idea/action-id', array('action' => 'view', 'id' => $ref['idea_id'])) ?>"><?php echo $ref['idea_title']; ?></a>
            </li>
        <?php endforeach; ?>
    </ul>
<?php else: ?>
    <p><i>There is no referece!</i></p>
<?php endif; ?>