<?php
$menu = [];
if ($this->laIdentity()) {
    $userId = $this->laIdentity()->usr_id;
    //add follow/unfollow
    if($this->ideaHelper()->isFollowed($idea->idea_id,$userId)){
        $menu['unfollow'] = ['url' => $this->url('idea/action-id', array('action' => 'unfollow', 'id' => $idea->idea_id))];
    }else{
        $menu['follow'] = ['url' => $this->url('idea/action-id', array('action' => 'follow', 'id' => $idea->idea_id))];
    }
}

$menu['evolution'] = ['url' => $this->url('idea/action-id', array('action' => 'evolution', 'id' => $idea->idea_id))];
if ($this->laIdentity() && $this->ideaPolicy()->canEvolve($idea, $userId)) {
    $menu['evolve'] = ['url' => $this->url('idea/action', array('action' => 'new'), array('query' => array('id' => $idea->idea_id)))];
}
if ($this->laIdentity() && $this->ideaPolicy()->canUpdate($idea, $userId)) {
    $menu['update'] = ['url' => $this->url('idea/action-id', array('action' => 'update', 'id' => $idea->idea_id))];
}
if ($this->laIdentity() && $this->ideaPolicy()->canRemove($idea, $userId)) {
    $menu['remove'] = ['url' => $this->url('idea/action-id', array('action' => 'hide', 'id' => $idea->idea_id))];
}
$menu['start_project'] = ['url' => $this->url('project/action', array('action' => 'new'), array('query' => array('idea' => $idea->idea_id)))];
if ($this->laIdentity() && $this->ideaPolicy()->canReport($idea, $userId)) {
    $menu['report'] = ['url' => $this->url('idea/action-id', array('action' => 'report', 'id' => $idea->idea_id))];
}
?>
<?php
$this->inlineScript()->captureStart();
?>
LApp.ideaMenu =  <?php echo json_encode($menu); ?>;

Ext.require('envitz.view.IdeaMenu');
Ext.onReady(function(){
try{
new Ext.create('envitz.view.IdeaMenu', {
ideaId:<?php echo $idea->idea_id ?>,
reportAlert:'<?php echo $this->translate("Found a violation? Send us a report."); ?>',
hideAlert:"<?php echo $this->translate("Remove this idea?"); ?>",
hideWarning:"<div style='color:red; text-align:center'>---<?php echo $this->translate('WARNING'); ?>---<BR><?php echo $this->translate('The idea will be permanently inaccessible from you and other users.<BR> Also note this action will not affect subsidiary ideas.'); ?></div>",
ideaInformation:"Idea:<SPAN style='display:inline-block;margin-left:20px;'><?php
    echo $idea->idea_title . " ";
    echo $idea->idea_categoryID != 0 ? "(" . $categoryTable->getById($idea->idea_categoryID)->cat_text . ")" : "";
    ?></SPAN>",
ideaCreator:'<div style="margin-left:50px;"><?php echo $originator->displayName(); ?></a><SPAN class="time"> posted at <?php echo $idea->idea_timeStamp; ?></SPAN></div>',
renderTo: 'idea_menu'

});
}catch(e){
console.log(e);
}


});
<?php
$this->inlineScript()->captureEnd();
?>
