<?php if ($ascending!==false): ?>
   <?php echo $this->ideaHelper()->getIcon($ascending);?>
    <a href="<?php echo $this->url('idea/action-id', array('action' => 'view', 'id' => $ascending->idea_id)) ?>"><?php echo $ascending->idea_title; ?></a>
<?php else: ?>
    <p>None ascending</p>
<?php endif; ?>

<?php if ($descending!==false): ?>
    <?php echo $this->ideaHelper()->getIcon($descending);?>
    <a href="<?php echo $this->url('idea/action-id', array('action' => 'view', 'id' => $descending->idea_id)) ?>"><?php echo $descending->idea_title; ?></a>

<?php else: ?>
    <p>None descending</p>
<?php endif; ?>
