<?php
$naviArray = array();
if (count($commentList) > 0): ?>
    <?php foreach ($commentList as $com): ?><!-- Begin comment block -->
        <div <?php
//prevent hackers from knowing the system comment ID!
if($com['iComm_readOnly']!=1):
	$naviArray[] = $com['iComm_id'];
?>
		id="userComm<?php echo $com['iComm_id'] ?>"
				data-commentId="<?php echo $com['iComm_id']; ?>"
				data-isCommenter="<?php echo $com['iComm_userId'] == $userId ? 1 : 0; ?>"
<?php endif; ?>>
            <div class="res_photo">
                <?php echo $this->usrHelper()->getIcon($com); ?>
            </div>
            <DL>
                <DT><SPAN class="commenter"><a target="_blank" href="<?php echo $this->url('people/profile', array('id' => $com['usr_id'])); ?>"><?php echo $this->displayName($com); ?></a></SPAN><SPAN class="time"> <?php echo $com['iComm_timeStamp']; ?></SPAN></DT>
                <DD class="body"><?php echo $com['iComm_comment']; ?></DD>
            </DL>
            <div class="navi" <?php if($com['iComm_readOnly']!=1){ echo "id=\"navi_{$com['iComm_id']}\"";} ?>></div>
        </div><!-- //END comment block -->
    <?php endforeach; ?>
<?php endif; ?>
<BR id="userCommsEnd" class="clear">

<div id="userCommAdds" name="userCommAdds"></div>
<BR class="clear">


<script type="text/javascript">
Ext.require([
	'envitz.view.envitzEditor',
	'envitz.view.ReportViolation',
	'envitz.view.RemoveComment',
	'envitz.view.CommentMenu',
	'envitz.view.CommentInsert'
	]);

LApp.thisPage = {
	mainID: <?php echo $idea->idea_id; ?>,
	isOwner: <?php echo $idea->idea_originator == $userId ? 1 : 0; ?>,
	navi: [<?php
for ($iComm=0; $iComm < count($naviArray); $iComm++) {
	echo $naviArray[$iComm] . ( $iComm < count($naviArray)-1? "," : "");
}
?>]
};

LApp.createNAVI = function (naviID) {
    try{
		new Ext.create('envitz.view.CommentMenu', {
			selector: 'userComm' + naviID,
			renderTo: 'navi_' + naviID,
                  reportUrl:'/idea/reportComment/'+naviID,
                  removeUrl:'/idea/deleteComment/'+LApp.thisPage.mainID+'?comment='+naviID,
			commentId: naviID
		});
    }catch(e){
		if(Ext.isGecko) console.debug(e);
    }
};

Ext.onReady(function() {
try{
	LApp.envitzEDIT = Ext.create('envitz.view.CommentInsert', {
		url: '<?php echo $this->url('idea/action', array('action' => 'addComment')) ?>',
		renderTo: 'userCommAdds'
	});
	LApp.envitzEDIT.down('#iComm_ideaId').setValue(LApp.thisPage.mainID);
	Ext.Array.forEach(LApp.thisPage.navi, LApp.createNAVI);

}catch(e){
	if(Ext.isGecko) console.debug(e);
}
});
	
elemListInsertAttr(document.getElementsByClassName('body'),['rel="nofollow"','target="_blank"']);         
          

</script>