<?php 
use DocumentManager\Model\ResourceType as Resource;
?>
<?php
$form = $this->form;
echo $this->form()->openTag($this->form);
?>
<div style="padding:20px;width:940px;z-index:999">
    <div style="color:#FFFFFF;background-color:#5880B3;padding:15px 20px;">Update Profile</div>
    <div style="background-color:#EAEFF5;padding:32px;">
        <?php echo $this->listErrors($context->errors); ?>
        <?php echo $this->flashMessenger()->render('error'); ?>
        <?php echo $this->flashMessenger()->render('success'); ?>
        <table>
            <tr>
                <td style="vertical-align:top;" colspan="2">
                    <div class="alert">
                        <?php echo sprintf($this->translate('*Maximum upload size is %s.'), \ImageManager\Model\ImgManager::getMaxUploadMessage()); ?>
                    </div>
                    <?php
                    echo $this->formElementErrors($form);
                    ?>
                    <?php if (isset($this->errors) && count($this->errors) > 0): ?>
                        <UL>
                            <?php foreach ($this->errors as $err): ?>
                                <LI><?php echo $err; ?></LI>
                            <?php endforeach; ?>
                        </UL>
                    <?php endif; ?>
                </td>
            </tr>
            <tr>
                <td style="vertical-align:top;"><?php echo $this->translate('Display Name'); ?></td>
                <td><?php echo $this->formElement($form->get('usr_displayName')); ?></td>
            </tr>
            <tr>
                <td style="vertical-align:top;"><?php echo $this->translate('Icon'); ?></td>
                <td>
                    <img src="<?php echo $this->url('process-image', array('path' => $this->pathManager()->buildUserRoutePath($user->usr_id,Resource::ICON,$user->usr_icon))); ?>" />
                    <br />
                    <?php echo $this->formElement($form->get('usr_icon')); ?>
                </td>
            </tr>
            <tr>
                <td style="vertical-align:top;"><?php echo $this->translate('Full Name'); ?></td>
                <td>
                    <?php echo $this->formElement($form->get('usr_fName')); ?>
                    <?php echo $this->formElement($form->get('usr_mName')); ?>
                    <?php echo $this->formElement($form->get('usr_lName')); ?>
                </td>
            </tr>
            <tr>
                <td style="vertical-align:top;"><?php echo $this->translate('About'); ?></td>
                <td>
                    <?php echo $this->formElement($form->get('usr_about')); ?>
                </td>
            </tr>
            <tr>
                <td style="vertical-align:top;"><?php echo $this->translate('Date of Birth'); ?></td>
                <td>
                    <?php echo $this->formElement($form->get('usr_dob')); ?>
                </td>
            </tr>
            <tr>
                <td style="vertical-align:top;"><?php echo $this->translate('Language'); ?></td>
                <td>
                    <?php
                    if ($form->get('usr_lang')->getValue() !== '') {
                        $form->get('usr_lang')->setEmptyOption(NULL);
                    }
                    ?>
                    <?php echo $this->formElement($form->get('usr_lang')); ?>
                </td>
            </tr>
            <tr>
                <td style="vertical-align:top;"><?php echo $this->translate('Gender'); ?></td>
                <td>
                    <?php echo $this->formElement($form->get('usr_gender')); ?>
                </td>
            </tr>
            <tr>
                <td><?php echo $this->translate('Contact'); ?></td>
                <td>
                    <table>
                        <tr>
                            <th><?php echo $this->translate('Email'); ?></th>
                            <th><?php echo $this->translate('Verified'); ?></th>
                            <th></th>
                        </tr>
                        <?php foreach ($this->emails as $email): ?>
                            <tr>
                                <td><?php echo $email->uEmail_email; ?></td>
                                <td><?php echo ($email->uEmail_isVerified == 1 ? $this->translate("Yes") : $this->translate('No')); ?></td>
                                <td>
                                    <a href="<?php echo $this->url('people/email', array('action' => 'delete', 'email' => $email->uEmail_email)); ?>"><?php echo $this->translate('Delete'); ?></a>
                                    <?php if ($email->uEmail_isVerified == 0): ?>
                                        <a href="<?php echo $this->url('people/email', array('action' => 'sendVerification', 'email' => $email->uEmail_email)); ?>"><?php echo $this->translate('Send Verify Email Again'); ?></a>
                                    <?php endif; ?>
                                </td>
                            </tr>
                        <?php endforeach ?>

                    </table>
                    <a href="<?php echo $this->url('people/createEmailPublic'); ?>"><?php echo $this->translate('Add Email'); ?></a>
                </td>
            </tr>
            <tr>
                <td><?php echo $this->translate('Skill'); ?></td>
                <td>
                    <?php if (count($skillList) > 0): ?>
                        <table>
                            <?php foreach ($skillList as $skill): ?>
                                <tr>
                                    <td>
                                        <?php echo $skill['stag_text']; ?>
                                    </td>
                                    <td>
                                        <a href="<?php echo $this->url('people/skill', array('action' => 'delete', 'id' => $skill['uSkll_id'])); ?>"><?php echo $this->translate('Delete'); ?></a>
                                    </td>

                                </tr>
                            <?php endforeach; ?>
                        </table>
                    <?php endif; ?>
                    <a href="<?php echo $this->url('people/skill', array('action' => 'create', 'id' => $user->usr_id)); ?>">Add Skill</a><BR />
                </td>
            </tr>
            <tr>
                <td><?php echo $this->translate('Education'); ?></td>
                <td>
                    <?php if (count($education) > 0): ?>
                        <table style="width: 500px;">
                            <?php foreach ($education as $ed): ?>
                                <tr>
                                    <td> <?php echo $ed['ed_name']; ?></td>
                                    <td><?php echo $ed['ed_fromDate']; ?></td>
                                    <td><?php echo ($ed['ed_toDate'] == '9999-12-31' ? $this->translate('Present') : $ed['ed_toDate']); ?></td>
                                    <td>
                                        <a href="<?php echo $this->url('people/education', array('action' => 'update', 'id' => $ed['ed_id'])) ?>">Edit</a>
                                        <a href="<?php echo $this->url('people/education', array('action' => 'delete', 'id' => $ed['ed_id'])) ?>">Delete</a>
                                    </td>
                                </tr>
                            <?php endforeach; ?>
                        </table>


                    <?php endif; ?>
                    <a href="<?php echo $this->url('people/education', array('action' => 'create', 'id' => $user->usr_id)); ?>">Add Education</a>
                </td>
            </tr>
            <tr>
                <td><?php echo $this->translate('Experience'); ?></td>
                <td>
                    <?php if (count($experience) > 0): ?>
                        <table style="width: 500px;">
                            <?php foreach ($experience as $xp): ?>
                                <tr>
                                    <td> <?php echo $xp['xp_name']; ?></td>
                                    <td><?php echo $xp['xp_fromDate']; ?></td>
                                    <td><?php echo ($xp['xp_toDate'] == '9999-12-31' ? $this->translate('Present') : $xp['xp_toDate']); ?></td>
                                    <td>
                                        <a href="<?php echo $this->url('people/experience', array('action' => 'update', 'id' => $xp['xp_id'])) ?>">Edit</a>
                                        <a href="<?php echo $this->url('people/experience', array('action' => 'delete', 'id' => $xp['xp_id'])) ?>">Delete</a>
                                    </td>
                                </tr>
                            <?php endforeach; ?>
                        </table>
                    <?php endif; ?>
                    <a href="<?php echo $this->url('people/experience', array('action' => 'create', 'id' => $user->usr_id)); ?>">Add Experience</a>
                </td>
            </tr>
        </table>
        <?php echo $this->formElement($form->get('submit')); ?>
    </div>
    <input type="hidden" id="MAX_FILE_SIZE" name="MAX_FILE_SIZE" value="<?php echo \ImageManager\Model\ImgManager::getMaxUploadSize(); ?>" />

</div>
<?php echo $this->form()->closeTag(); ?>
