<a href="<?php echo $this->url('people/action-id', array('action' => 'edit', 'id' => $userId)); ?>">Back</a>
<?php if (count($this->errors) > 0): ?>
    <ul>
        <?php foreach ($this->errors as $err): ?>
            <li><?php echo $err; ?></li>
        <?php endforeach; ?>
    </ul>
<?php endif; ?>
<?php echo $this->form()->openTag($this->form); ?>
<?php
echo $this->formCollection($this->form);
?>
<?php echo $this->form()->closeTag(); ?>
<?php if (count($experience) > 0): ?>
    Experience:
    <ul>
        <?php foreach ($experience as $xp): ?>
            <li>
                <?php echo $xp['xp_name']; ?>
            </li>
        <?php endforeach; ?>
    </ul>
<?php endif; ?>


