<?php if (count($people) > 0): ?>
    <ul>
        <?php foreach ($people as $p): ?>
            <li>
                <a href="<?php echo $this->url('people/profile',array('id'=>$p['usr_id']));?>"><?php echo \Users\Model\User::getDisplayName($p);?></a>
                 <br /> <?php echo $this->followUserButton($p['usr_id']);?>
            </li>
        <?php endforeach; ?> 
    </ul>

<?php endif; ?>


