<?php $this->headStyle()->captureStart() ?>

ul.tab{display:block;min-width:80%;}
div.clear-tab{clear:both;border-bottom:2px solid #5880B3;}
ul.tab li{display:inline-block;list-style-type:none;min-width:120px;float:right;}
ul.tab li a{display:block;text-decoration:none; background-color:gray;padding:10px;color:white;}
ul.tab li a.selected{background-color:darkblue;}
div.tab-content.display{display:block;}
div.tab-content.hide{display:none;}
<?php $this->headStyle()->captureEnd() ?>
<div class="box" style="padding: 10px;">
    <div class="subject">
        <ul class="tab">
            <li><a href="<?php echo $this->url('people/follower');?>"><?php echo $this->translate('Followers'); ?></a></li>
            <li><a class="selected"  href="#"><?php echo $this->translate('Following'); ?></a></li>
        </ul>
    </div>
    <div class="clear-tab"></div>
    <div class="tab">
        <div class="tab-content display" id="following">
             <?php echo $this->usrHelper()->getFollowing($userId); ?>
        </div>
        <div class="tab-content hide" id="followers">
           
        </div>
    </div>
</div>
