<?php $this->headStyle()->captureStart() ?>

ul.tab{display:block;min-width:80%;}
div.clear-tab{clear:both;border-bottom:2px solid #5880B3;}
ul.tab li{display:inline-block;list-style-type:none;min-width:120px;float:right;}
ul.tab li a{display:block;text-decoration:none; background-color:gray;padding:10px;color:white;}
ul.tab li a.selected{background-color:darkblue;}
div.tab-content.display{display:block;}
div.tab-content.hide{display:none;}
<?php $this->headStyle()->captureEnd() ?>
<div class="box">
    <div class="subject">
        <H2>
            <!--<img src="<?php //echo $this->url('process-image', array('path' => $this->pathManager()->buildUserRoutePath($user->usr_id, Resource::ICON, $user->usr_icon)));   ?>" height="32" />--> 
            <?php echo $this->usrHelper()->getIcon($user); ?>
            <?php echo $user->usr_displayName; ?>
            <div class="follow" style="float: right;display: inline-block;width: 40px;padding-top: 10px;">
                <?php echo $this->usrHelper()->follow($user->usr_id); ?>
            </div>
        </H2></div>
    <div style="margin:10px;">
        <P><?php echo $user->usr_about; ?></P>
        <table>
            <tr>
                <td><?php echo $this->translate('Birthday'); ?>:</td>
                <td><?php echo $this->usrHelper()->formatDob($user->usr_dob); ?></td>
            </tr>
            <tr>
                <td><?php echo $this->translate('Gender'); ?>:</td>
                <td>
                    <?php echo $this->usrHelper()->getGender($user->usr_gender); ?>
                </td>
            </tr>
            <tr>
                <td style="vertical-align: top;"><?php echo $this->translate('Language'); ?>:</td>
                <td>
                    <?php echo $this->usrHelper()->getLangList($user->usr_id); ?>
                </td>
            </tr>
            <tr>
                <td style="vertical-align: top;"><?php echo $this->translate('Location'); ?>:</td>
                <td>
                    <?php echo $this->usrHelper()->getLocationList($user->usr_id); ?>
                </td>
            </tr>
            <tr style="vertical-align: top;">
                <td><?php echo $this->translate('Skills'); ?>:</td>
                <td>
                    <?php echo $this->usrHelper()->getSkillList($user->usr_id); ?>
                </td>
            </tr>
            <tr style="vertical-align: top;">
                <td><?php echo $this->translate('Certifications'); ?>:</td>
                <td>
                    <?php echo $this->usrHelper()->getCertList($user->usr_id); ?>
                </td>
            </tr>
        </table>
        <?php echo $this->usrHelper()->getContactList($user->usr_id); ?> 
        <?php echo $this->usrHelper()->getEdList($user->usr_id); ?>
        <?php echo $this->usrHelper()->getXpList($user->usr_id); ?>



    </div>
</div>
<div class="box">
    <div class="subject">
        <UL class="tab">
            <LI>
                <a href="#projects"><?php echo $this->translate('Projects'); ?>
                    <?php echo ($projects = $this->usrHelper()->countProject($user->usr_id)) > 0 ? "(" . $projects . ")" : ""; ?>
                </a>
            </LI>
            <LI>
                <a class="selected" href="#ideas"><?php echo $this->translate('Ideas'); ?>
                    <?php echo ($ideas = $this->usrHelper()->countIdea($user->usr_id)) > 0 ? "(" . $ideas . ")" : ""; ?>
                </a>
            </LI>
        </UL>
    </div>
    <div class="clear-tab"></div>
    <div class="tab">
        <div class="tab-content" id="ideas">
            <?php echo $this->usrHelper()->getIdeas($user->usr_id); ?>
        </div>
        <div class="tab-content hide" id="projects">
            <?php echo $this->usrHelper()->getProjects($user->usr_id); ?>
        </div>
    </div>
</div>

<script type="text/javascript">

/*
	We should change this to use Sencha Tabs with a theme applied.
	https://github.com/LINKAIDE/envitz.social/issues/257
	
*/
    Ext.onReady(function() {
        Ext.select('ul.tab a').on('click', function(e, t) {
            Ext.select('ul.tab a').removeCls('selected');
            var el = Ext.get(this);
            el.addCls('selected');
            //
            Ext.select('div.tab-content').removeCls('display').addCls('hide');
            //
            var id = el.getAttribute('href');
            id = id.replace('#', '');
            Ext.get(id).removeCls('hide').addCls('display');

        });
    });
</script>