<?php ?>
<script type="text/javascript">
    LApp.formData =<?php echo json_encode($data); ?>;
</script>

<div id="search-engine-advance-panel"></div>
<?php if (isset($people) && count($people) > 0): ?>
    <div id="people-result" class="box">
        <H2><?php echo $this->translate('People'); ?> (<?php echo count($people); ?>)</H2>

        <OL>
            <?php foreach ($people as $p): ?>
                <LI><a href="<?php echo $this->url('people/profile', array('id' => $p['usr_id'])); ?>"> <?php echo \Users\Model\DbEntity\User::getDisplayName($p) ?></a>
                    <?php if (isset($userId)): ?>
                        <BR /> <?php echo $this->followUserButton($p['usr_id']); ?>
                    <?php endif; ?>
                </LI>
            <?php endforeach; ?>
        </OL>
    </div>
<?php endif; ?>
<?php if (isset($ideas) && count($ideas) > 0): ?>

    <div id="idea-result" class="box">
        <H2><?php echo $this->translate('Ideas'); ?> (<?php echo count($ideas); ?>)</H2>
        <OL>
            <?php foreach ($ideas as $id): ?>
                <LI> <a href="<?php echo $this->url('idea/action-id', array('action' => 'view', 'id' => $id['idea_id'])) ?>"><?php echo $id['idea_title']; ?></a>
                    <?php if (isset($userId)): ?>
                        <BR /><?php echo $this->followIdeaButton($userId, $id['idea_id']); ?>
                    <?php endif; ?>
                </LI>
            <?php endforeach; ?>
        </OL>

    </div>
<?php endif; ?>
<?php if (isset($projects) && count($projects) > 0): ?>
    <div id="project-result" class="box">
        <H2><?php echo $this->translate('Projects'); ?> (<?php echo count($projects); ?>)</H2>
        <OL>
            <?php foreach ($projects as $proj): ?>
                <LI> <a href="<?php echo $this->url('project/action-id', array('action' => 'view', 'id' => $proj['proj_id'])) ?>"><?php echo $proj['proj_title']; ?></a></LI>
            <?php endforeach; ?>
        </OL>
    </div>
<?php endif; ?>

<?php if ($this->laIdentity()): ?>
    <?php if (isset($messages) && count($messages) > 0): ?>
        <div id="message-result" class="box">
            <H2><?php echo $this->translate('Messages'); ?> (<?php echo count($messages); ?>)</H2>
            <OL>
                <?php foreach ($messages as $item): ?>
                    <LI> <a href="<?php echo $this->url('message/action-id', array('action' => ($item['msg_senderID'] == $userId ? 'sentItem' : 'view'), 'id' => $item['msg_id'])) ?>"><?php echo $item['msg_subject']; ?></a></LI>
                <?php endforeach; ?>
            </OL>
        </div>
    <?php endif; ?>

    <?php if (isset($idea_comments) && count($idea_comments) > 0): ?>
        <div id="message-result" class="box">
            <H2><?php echo $this->translate('Idea Comments'); ?> (<?php echo count($idea_comments); ?>)</H2>
            <OL>
                <?php foreach ($idea_comments as $item): ?>
                    <LI> <a href="<?php echo $this->url('idea/action-id', array('action' => 'view', 'id' => $item['iComm_ideaId'])) ?>"><?php echo $item['iComm_comment']; ?></a></LI>
                <?php endforeach; ?>
            </OL>
        </div>
    <?php endif; ?>

    <?php if (isset($project_comments) && count($project_comments) > 0): ?>
        <div id="message-result" class="box">
            <H2><?php echo $this->translate('Project Comments'); ?> (<?php echo count($project_comments); ?>)</H2>
            <OL>
                <?php foreach ($project_comments as $item): ?>
                    <LI> <a href="<?php echo $this->url('project/action-id', array('action' => 'view', 'id' => $item['prjW_projID'])) ?>"><?php echo $item['prjW_comment']; ?></a></LI>
                <?php endforeach; ?>
            </OL>
        </div>
    <?php endif; ?>
<?php endif; ?>
