<!-- join widget -->
  <div id="TopJoinArea">
    <P>Not a member?<BR>Join us today!</P>
    <div class="signIn">
	<form method="post" class="join_form" action="<?php echo $this->url('user',array('action'=>'join'));?>">
		<input type="hidden" name="x" id="x" value="">
		<input type="hidden" name="y" id="y" value="">
		<input placeholder="Name" id="join_fName" name="join_fName" type="text" required><BR />
		<input placeholder="Email" id="join_email" name="join_email" type="email" required><BR />
		<input value="Join" class="submit join" type="submit" style="width: 100px;">
	</form>
	</div>
  </div>
<!-- //join widget -->
<?php
$this->inlineScript()->captureStart();
?>
Ext.onReady(function(){
    Ext.select('form input.join').on('click', function(e){
        e.preventDefault();
        //validations
        var errStr="",
                x = Ext.get('x'),
                y = Ext.get('y'),
                fName = Ext.get('join_fName'),
                jEmail = Ext.get('join_email');

        if(!fName.getValue()){
            errStr += "Name cannot be empty.<BR />";
        }

        if(!jEmail.getValue()){
            errStr += "Email cannot be empty.<BR />";
        }else if(!Ext.data.validations.email({}, Ext.get('join_email').getValue())){
            errStr += "Email is not valid.<BR />";
        }

        if(errStr !== ""){
            Alert('Join Request - Information', errStr);
        }else{
            Ext.Ajax.request({
                url: LApp.guestJoin,
                params: {
                    join_fName: fName.getValue(),
                    join_email: jEmail.getValue(),
                    x: x.getValue(),
                    y: y.getValue()
                },
                success: function(response){
                    var svrMsg = Ext.JSON.decode(response.responseText);
                     Alert("Join Request - Success", svrMsg.msg);
                },
                failure: function(response){
                console.log(response);
                    Alert("Join Request - Error", "There is an error in connection");
                }
            });
        }
        
        
    });
});
<?php
$this->inlineScript()->captureEnd();
?>