<p><?php echo sprintf($this->translate('THIS IS BEING SENT FROM AN UNMONITORED MAILBOX. PLEASE DO
    NOT REPLY TO THIS EMAIL. IF YOU HAVE QUESTIONS, PLEASE
    CONTACT %shelp@linspira.com%s.'), '<a href="mailto:help@linspira.com">', '</a>'); ?></p>

<p><?php echo sprintf($this->translate('Hi %s'),$user->getFullName()); ?>,</p>

<p><?php echo $this->translate("You've successfully changed your password.");?></p>

<p><?php echo $this->translate("Thank you,");?></p>

<p><?php echo $this->translate("The Linspira Team");?></p>
<p>
    <?php echo sprintf($this->translate('Customer Service at %sLinspira.com%s [Tokyo, Japan]'), '<a href="http://linspira.com">', '</a>'); ?><br />
    <?php echo sprintf($this->translate('Sent to: %s'), $user->usr_email); ?>
</p>

