<p><?php echo sprintf($this->translate('THIS IS BEING SENT FROM AN UNMONITORED MAILBOX. PLEASE DO
    NOT REPLY TO THIS EMAIL. IF YOU HAVE QUESTIONS, PLEASE
    CONTACT %shelp@linspira.com%s.'),'<a href="mailto:help@linspira.com">','</a>');?></p>
<p>
    <?php echo $this->translate('**Registration Completion on Linspira');?><br />
    -------------------------</p>

<p><?php echo sprintf($this->translate('Hello %s'),$name);?>,</p>

<p><?php echo sprintf($this->translate('You have requested to create an account on %sLinspira.com%s.
    Please follow this link to complete your registration'),'<a href="http://linspira.com">','</a>'); ?>
    :
    <a href="<?php echo $this->url('user', array('action' => 'registration'), array('query' => array('key' => $key), 'force_canonical' => true)) ?>"><?php echo $this->url('user', array('action' => 'registration'), array('query' => array('key' => $key), 'force_canonical' => true)) ?></a>
</p>
<p>
    <?php echo $this->translate("If your browser doesn't open when you click the link, please
    cut and paste the link into the address bar on your browser.
    When you reach the registration page using the link, you'll find
    instructions for completing the registration process.");?>
</p>
<p>
    <?php echo $this->translate('If you haven\'t requested to join, please ignore this email.');?><br />

    -------------------------</p>
<p>
    <?php echo $this->translate('**Help');?><br />
    <?php echo sprintf($this->translate('If you have any questions, contact one of our Customer
    Service associates at %shelp@linspira.com%s.'),'<a href="mailto:help@linspira.com">','</a>');?></p>
<p>
   <?php echo $this->translate('Sincerely,');?>
</p>
<p>
    <?php echo sprintf($this->translate('Customer Service at %sLinspira.com%s [Tokyo, Japan]'),'<a href="http://linspira.com">','</a>');?><br />
    <?php echo sprintf($this->translate('Sent to: %s'),$email); ?>
</p>