<P><?php echo sprintf($this->translate('THIS IS BEING SENT FROM AN UNMONITORED MAILBOX. PLEASE DO
    NOT REPLY TO THIS EMAIL. IF YOU HAVE QUESTIONS, PLEASE
    CONTACT %shelp@linspira.com%s.'), '<a href="mailto:help@linspira.com">', '</a>'); ?></P>

<P><?php echo sprintf($this->translate('Dear %s'),$user->getFullName()); ?>,</P>


<P><?php echo sprintf($this->translate('You have successfully registered on %sLinspira.com%s. Get your idea out there before someone else does!'),'<a href="http://linspira.com">','</a>');?>
 </P>

<P>
    <?php echo $this->translate('**Help'); ?><BR />
    <?php echo sprintf($this->translate('If you have any questions, contact one of our Customer
    Service associates at %shelp@linspira.com%s.'), '<a href="mailto:help@linspira.com">', '</a>'); ?></P>
<P>
    <?php echo $this->translate('Sincerely,'); ?>
</P>
<P>
    <?php echo sprintf($this->translate('Customer Service at %sLinspira.com%s [Tokyo, Japan]'), '<a href="http://linspira.com">', '</a>'); ?><BR />
    <?php echo sprintf($this->translate('Sent to: %s'), $user->usr_email); ?>
</P>