<div class="box">
    <div class="subject"><H2><?php echo $this->translate('Forgot password?'); ?></H2></div>
    <div style="margin:10px;">
        <div style="padding:32px;">
            <?php echo sprintf($this->translate('Password recovery email is sent to %s'), $this->email); ?><br /><br />
            <?php echo sprintf($this->translate('Please follow the instruction sent from %sjoin@linspira.com%s and complete the recovery.'), '<a href="mailto:join@linspira.com?subject=&amp;body=">', '</a>') ?><br /><br />
            <?php echo sprintf($this->translate('Not receiving email? Please visit our %sHelp Center%s.'),'<a href="'.$this->url('help').'">','</a>'); ?><br />
            
        </div>
    </div>
</div>
