<?php if (count($flashMessages)) : ?>
    <ul>
        <?php foreach ($flashMessages as $msg) : ?>
            <li><?php echo $msg; ?></li>
        <?php endforeach; ?>
    </ul>
<?php endif; ?>
<?php if (isset($registered) && $registered == true): ?>
    <div class="joinBox">
        <div class="subject"><H2><?php echo $this->translate('Join Error'); ?></H2></div>
        <div style="margin:10px;">
            <div style="padding:32px;">
                <p><?php echo sprintf($this->translate('The email you submitted is already registered! Would you like to %schange your password%s in case you forgot it'), '<a href="' . $this->url('user', array('action' => 'forgot')) . '">', '</a>'); ?></p>
            </div>
        </div>
    </div>

<?php else: ?>
    <?php
    print_r($stat);
    $form = $this->form;
    $form->prepare();
    //$form->setAttribute('action', $this->url(NULL, array('controller'=>'User', 'action' => 'join')));
    $form->setAttribute('method', 'post');

    echo $this->form()->openTag($form);
    ?>
    <dl class="zend_form">

        <dt><?php echo $this->translate($this->formLabel($form->get('join_fName'))); ?></dt>
        <dd><?php
            echo $this->formElement($form->get('join_fName'));
            echo $this->formElementErrors($form->get('join_fName'));
            ?></dd>
        <dt><?php echo $this->formLabel($form->get('join_email')); ?></dt>
        <dd><?php
            echo $this->formElement($form->get('join_email'));
            echo $this->formElementErrors($form->get('join_email'));
            ?></dd>
        <dd><?php
            echo $this->formElement($form->get('submit'));
            echo $this->formElementErrors($form->get('submit'));
            ?></dd>

    </dl>
    <?php echo $this->form()->closeTag() ?>
<?php endif; ?>

