<?php $this->inlineScript()->appendScript("
    window.onbeforeunload=function(e){
       // return 'Are you sure you want to cancel the signup?';

    };
    
   var btn = document.getElementById('cancel');
    btn.addEventListener('click',function(e){
        var msg=confirm('Are you sure you want to cancel?');
        if(!msg){
            e.preventDefault();
        }
        
    });
"); ?>
<?php echo $this->listErrors($context->errors); ?>
<?php
$form = $this->form;
echo $this->form()->openTag($this->form);
echo $this->formElementErrors($form);
?>
<?php echo $this->formElement($form->get('hidden_session')); ?>
<div style="padding:20px;width:940px;">
    <div style="color:#FFFFFF;background-color:#5880B3;padding:15px 20px;">Sign up</div>
    <div style="background-color:#EAEFF5;padding:32px;">
        <?php echo sprintf($this->translate('Hello %s, Welcome to Linpira.'), $fullname); ?><br />
        <?php echo $this->translate('Please provide the following information to register your membership.'); ?><br />
        <table>
            <tr><td style="vertical-align:top;"><?php echo $this->translate('Email'); ?></td><td><?php echo $this->email; ?></td></tr>
            <tr>
                <td style="vertical-align:top;"><?php echo $this->translate('Full Name'); ?></td>
                <td>
                    <?php echo $this->formElement($form->get('usr_fName')); ?>
                    <?php echo $this->formElement($form->get('usr_mName')); ?>
                    <?php echo $this->formElement($form->get('usr_lName')); ?>
                </td>
            </tr>
            <tr>
                <td style="vertical-align:top;"><?php echo $this->translate('Address'); ?></td>
                <td>
                    <?php echo $this->formElement($form->get('uAddr_address1')); ?>
                    <?php echo $this->formElement($form->get('uAddr_address2')); ?><br />
                    <?php echo $this->formElement($form->get('uAddr_city')); ?>
                    <?php echo $this->formElement($form->get('uAddr_state')); ?>
                    <?php echo $this->formElement($form->get('uAddr_ZIP')); ?>
                    <?php echo $this->formElement($form->get('uAddr_country')); ?>
                </td>
            </tr>
            <tr>
                <td style="vertical-align:top;"><?php echo $this->translate('Telephone'); ?></td>
                <td>
                    <?php echo $this->formElement($form->get('uPhon_number')); ?>
                </td>
            </tr>
            <tr>
                <td style="vertical-align:top;"><?php echo $this->translate('Language'); ?></td>
                <td>
                    <?php echo $this->formElement($form->get('usr_lang')); ?>
                </td>
            </tr>
            <tr>
                <td style="vertical-align:top;"><?php echo $this->translate('Password'); ?></td>
                <td>
                    <?php echo $this->formElement($form->get('usr_password')); ?><span style="color:#ff0000;padding:0 5px;">&lt;Password validation&gt;</span><br />
                    <?php echo $this->formElement($form->get('confirm_password')); ?><span style="color:#ff0000;padding:0 5px;">&lt;Password validation&gt;</span>
                </td>
            </tr>
            <tr>
                <td style="vertical-align:top;"><?php echo $this->translate('Are you human?'); ?></td>
                <td>
                    <?php echo $this->formElement($form->get('captcha')); ?>
                </td>
            </tr>
        </table>
        <?php echo $this->formElement($form->get('submit')); ?>
        <input type="button" name="cancel" id="cancel" value="Cancel" style="padding:3px 25px;" />
    </div>

</div>
<?php echo $this->form()->closeTag(); ?>