<h1>Change Email</h1>
<?php echo $this->listErrors($this->context->errors); ?>
<?php echo $this->listSuccess($this->context->success); ?>
<?php if ($this->is_success): ?>
    <p><?php echo $this->translate('Please check your email and follow the link to finish your email changing.'); ?></p>
<?php else: ?>
    <?php echo $this->form()->openTag($this->form); ?>
    <?php
    echo $this->formCollection($this->form);
    ?>
    <?php echo $this->form()->closeTag(); ?>
<?php endif; ?>

