<?php

$form = $this->form;
$form->prepare();
$form->setAttribute('method', 'post');
?>
<div class="passwordBox">
    <div class="subject"><H2><?php echo $this->translate('Reset your password'); ?></H2></div>
    <div style="margin:10px;">
        <?php 
        echo $this->listErrors($this->context->errors); 
        // If token has not yet expired, show the secret question
        if(!$isTokenExpired):
        ?>
        <div style="margin: 10px 0;">
            <p><?php echo $this->translate('Please answer your secret question in order to reset the password'); ?></p>
            <p><?php echo sprintf($this->translate('If you don’t remember, please contact our %sHelp Center%s.'), '<a href="' . $this->url('help') . '">', '</a>'); ?></p>
        </div>
        <?php echo $this->form()->openTag($form); ?>
        <table>
            <tr>
                <td style="width: 100px;"><?php echo $this->translate('Question'); ?></td>
                <td><?php echo $question; ?></td>
            </tr>
            <tr>
                <td style="width: 100px;"></td>
                <td><?php echo $this->formElement($form->get('answer')); ?></td>
            </tr>
            <tr>
                <td>
                    <?php
                    echo $this->formElement($form->get('user_id'));
                    ?>
                </td>
                <td>
                    <input type="submit" value="<?php echo $this->translate('Next'); ?>" />
                    <input type="submit" onclick="window.location = '/';return false;" value="<?php echo $this->translate('Cancel'); ?>" />
                </td>
            </tr>
        </table>
        <?php echo $this->form()->closeTag(); endif; ?>
    </div>

</div>

