<?php echo (!empty($errormsg)) ? '<ul>'.$errormsg.'</ul>' : ''; ?>
<?php echo $this->filterErrors($form);?>
<?php echo $this->listSuccess($this->context->success); ?>

<?php $this->headStyle()->captureStart() ?>

table.email-list td{padding:5px;min-width:80px;}
<?php $this->headStyle()->captureEnd() ?>

<script type="text/javascript">
    LApp.messages.full_name = "<?php echo $this->translate('Full Name'); ?>";
    LApp.formData =<?php echo json_encode($data); ?>;
</script>

<div><?php //echo 'testing - '. $data['account']; ?>
<div class="box_idea">
	<div class="box1" id="user-settings-panel"></div>
</div>