<h1>Setting page</h1>
<?php echo $this->listErrors($this->context->errors); ?>
<?php echo $this->listSuccess($this->context->success); ?>
<?php echo $this->formElementErrors($form); ?>
<?php echo $this->form()->openTag($this->form); ?>

<table>
    <tr>
        <td style="vertical-align:top;"><?php echo $this->translate('User account'); ?></td>
        <td>
            <i> <?php echo $this->laIdentity()->usr_username; ?> (<?php echo $this->translate('Select primary email at Emails'); ?>)</i>
        </td>
    </tr>
    <tr>
        <td style="vertical-align:top;"><?php echo $this->translate('Full Name'); ?></td>
        <td>
            <?php echo $this->formElement($form->get('usr_fName')); ?>
            <?php echo $this->formElement($form->get('usr_mName')); ?>
            <?php echo $this->formElement($form->get('usr_lName')); ?>
        </td>
    </tr>
    <tr>
        <td style="vertical-align:top;"><?php echo $this->translate('Address'); ?></td>
        <td>
            <?php echo $this->formElement($form->get('uAddr_address1')); ?>
            <?php echo $this->formElement($form->get('uAddr_address2')); ?><br />
            <?php echo $this->formElement($form->get('uAddr_city')); ?>
            <?php echo $this->formElement($form->get('uAddr_state')); ?>
            <?php echo $this->formElement($form->get('uAddr_ZIP')); ?>
            <?php echo $this->formElement($form->get('uAddr_country')); ?>
        </td>
    </tr>
    <tr>
        <td style="vertical-align:top;"><?php echo $this->translate('Telephone'); ?></td>
        <td>
            <?php echo $this->formElement($form->get('uPhon_number')); ?>
        </td>
    </tr>
    <tr>
        <td style="vertical-align:top;"><?php echo $this->translate('Language'); ?></td>
        <td>
            <?php
            if ($form->get('usr_lang')->getValue() !== '') {
                $form->get('usr_lang')->setEmptyOption(NULL);
            }
            ?>
            <?php echo $this->formElement($form->get('usr_lang')); ?>
        </td>
    </tr>
    <tr>
        <td style="vertical-align:top;"><?php echo $this->translate('Password'); ?></td>
        <td>
            <?php echo $this->formElement($form->get('password')); ?><br />
            <?php echo $this->formElement($form->get('confirm_password')); ?>
        </td>
    </tr>
    <tr>
        <td style="vertical-align:top;"><?php echo $this->translate('Email'); ?></td>
        <td>
            <!--Email list-->
            <table>
                <tr>
                    <th><?php echo $this->translate('Type'); ?></th>
                    <th><?php echo $this->translate('Email'); ?></th>
                    <th><?php echo $this->translate('Verified'); ?></th>
                    <th></th>
                </tr>
                <tr>
                    <td><?php echo $this->translate('Primary'); ?></td>
                    <td><?php echo $this->laIdentity()->usr_username; ?></td>
                    <td><?php echo $this->translate('Yes'); ?></td>
                    <td></td>
                </tr>
                <?php foreach ($this->emails as $email): ?>
                    <?php if ($email->uEmail_email == $this->laIdentity()->usr_username) continue; ?>
                    <tr>
                        <td><?php echo $this->translate('Alternative'); ?></td>
                        <td><?php echo $email->uEmail_email; ?></td>
                        <td><?php echo ($email->uEmail_isVerified == 1 ? $this->translate("Yes") : $this->translate('No')); ?></td>
                        <td>
                            <?php if ($email->uEmail_isVerified == 1): ?>
                                <a href="<?php echo $this->url('people/email', array('action' => 'setPrimary', 'email' => $email->uEmail_email)); ?>"><?php echo $this->translate('Set primary'); ?></a> 
                            <?php endif; ?>
                            <a href="<?php echo $this->url('people/email', array('action' => 'delete', 'email' => $email->uEmail_email)); ?>"><?php echo $this->translate('Delete'); ?></a>
                            <?php if ($email->uEmail_isVerified == 0): ?>
                                <a href="<?php echo $this->url('people/email', array('action' => 'sendVerification', 'email' => $email->uEmail_email)); ?>"><?php echo $this->translate('Send Verify Email Again'); ?></a>
                            <?php endif; ?>
                        </td>
                    </tr>
                <?php endforeach ?>

            </table>
            <a href="<?php echo $this->url('people/createEmail'); ?>"><?php echo $this->translate('Add Email'); ?></a>
        </td>
    </tr>
    <tr>
        <td style="vertical-align: top;"><?php echo $this->translate('Secrect Q&A'); ?></td>
        <td>
            <?php echo $this->formElement($form->get('usr_secretQ')); ?><br />
            <?php echo $this->formElement($form->get('secretA')); ?>
        </td>
    </tr>
</table>

<?php echo $this->formElement($form->get('submit')); ?>
<?php echo $this->form()->closeTag(); ?>