<?php echo $this->listErrors($context->errors); ?>

<?php 
//print_r($sessid); 
/*foreach($sessid as $key => $val):
    echo $val."<br>";
endforeach;*/

?>
<br>
<?php //print_r($currsesid); ?>

<span style="display: inline-block; border: 1px solid #EAEFF5; padding: 35px;">
<h2>Login</h2>



<form action="<?php echo($this->url(NULL, array('controller' => 'Login', 'action' => 'signin'))); ?>" method="post" name="Login" id="Login">
<dl class="form">
    <dt><label for="usr_username">User Name</label></dt>
    <dd><input type="email" name="usr_username" required="required" placeholder="User Name" value=""></dd>

    <dt><label for="usr_password">Password</label></dt>
    <dd><input type="password" name="usr_password" required="required" placeholder="Password" value=""></dd>
    <dt><input type="checkbox" name="rememberme" id="rememberme" value="1"> <label style="display: inline;" for="rememberme">Remember me</label> </dt>
<BR>
    <dd><input type="submit" name="submit" value="Login"></dd>

</dl>
</form>
<a href="/forgot">Forgot passoword?</a>
</span>





<span style="width:100px; display: inline-block;">&nbsp;</span>

<span style="display: inline-block; border: 1px solid #EAEFF5; padding: 35px; vertical-align: top;">
<h2>New User</h2>
<form id="pre-signup" name="pre-signup" method="post" action="/join"><dl class="zend_form">

    <dt><label for="join_fName">Name</label></dt>
    <dd><input type="text" value="" placeholder="Name" required="required" name="join_fName"></dd>
    <dt><label for="join_email">Email</label></dt>
    <dd><input type="email" value="" placeholder="Email" required="required" name="join_email"></dd>
    <dd>
	<BR>
<input type="submit" value="Join" name="submit"></dd>

</dl>
</form>
</span>