
<?php if (count($data) > 0): ?>
    <table class="grid-view">
        <?php foreach ($data as $d): ?>
            <tr>
                <td style="min-width: 250px;">
                    <a class="person" href="<?php echo $this->url('people/profile', array('id' => $d['usr_id'])); ?>">
                    <?php echo $this->usrHelper()->getIcon($d);?>
                     <?php echo $this->displayName($d); ?>
                    </a>
                </td>
                <td style="min-width: 200px;">
                    <?php echo $this->usrHelper()->getCurrentJob($d['usr_id']);?>
                </td>
                <td>
                    <?php if ($this->usrPolicy()->canReceiveMessage($d['usr_id'])): ?>
                        <a href="<?php echo $this->url('message/action', array('action' => 'new'), array('query' => array('user' => $d['usr_id']))); ?>">
                            <img src="<?php echo $this->basePath(); ?>/images/message.png" height="24" />
                        </a>
                    <?php endif; ?>
                </td>
                <td>
                    <?php echo $this->usrHelper()->follow($d['usr_id']);?>
                </td>
            </tr>
        <?php endforeach; ?>
    </table>
<?php else: ?>
 <?php if ($this->usrHelper()->isCurrentUser($userId)): ?>
        <I><?php echo $this->translate("Not a follower? We understand. Perhaps you're more of a leader then?"); ?></I>
    <?php else: ?>
        <I><?php echo $this->translate('This user has not started following anyone yet.'); ?></I>
    <?php endif; ?>
    
<?php endif; ?>
