
<?php if (count($data) > 0): ?>
    <table class="grid-view">
        <?php foreach ($data as $d): ?>
            <tr>
                <td>
                    <a class="idea" href="<?php echo $this->url('idea/action-id', array('action' => 'view', 'id' => $d['idea_id'])); ?>">
                        <?php echo $this->ideaHelper()->getIcon($d); ?>
                        <?php echo $d['idea_title']; ?> <?php echo ($d['cat_text'] ? "(" . $d['cat_text'] . ")" : ""); ?>
                    </a>
                </td>
                <td style="vertical-align: bottom;min-width: 300px;">
                    <a class="person" href="<?php echo $this->url('people/profile', array('id' => $d['idea_originator'])); ?>">
                        <?php echo $this->usrHelper()->getIcon($d); ?>
                        <?php echo $this->displayName($d); ?>
                    </a>
                    <?php echo $this->translate('posted at'); ?> <?php echo $d['idea_timeStamp']; ?>
                </td>
                <td style="vertical-align: bottom;">
                    <?php echo $this->ideaHelper()->followButton((object)$d) ?>
                </td>
            </tr>
        <?php endforeach; ?>
    </table>
<?php else: ?>
    <?php if ($this->usrHelper()->isCurrentUser($userId)): ?>
        <a href="<?php echo $this->url('idea/action', array('action' => 'new')); ?>"> <I><?php echo $this->translate('You have not created any ideas yet. How about creating one?'); ?></I></a>
    <?php else: ?>
        <I><?php echo $this->translate('This user has no posted ideas yet.'); ?></I>
    <?php endif; ?>

<?php endif; ?>
