<?php
    if(isset($_SERVER['HTTPS'])){
        $protocol = ($_SERVER['HTTPS'] && $_SERVER['HTTPS'] != "off") ? "https" : "http";
    } else {
        $protocol = 'http';
    }                    
?>
<?php if ($usr_icon === "" || $usr_icon === NULL): ?>
    <a class="person" href="<?php echo $protocol. "://" .$_SERVER['SERVER_NAME']. $this->url('people/profile', ['id' => $usr_id]); ?>">
        
        <img title="<?php echo $this->displayName($user); ?>" alt="<?php echo $this->displayName($user); ?>" src="<?php echo $protocol. "://" .$_SERVER['SERVER_NAME'].'/images/photo001.png'; ?>" style="height:32px;width:32px;" />
        <!--<span title="<?php echo $this->displayName($user); ?>" class="noIconAvatar" style="height: 32px;width: 32px;display: inline-block;"></span>-->
    </a>
<?php else: ?>
    <?php //if ($this->laIdentity() && ($usr_id != $this->laIdentity()->usr_id)): ?>
    <a class="person" href="<?php echo $protocol. "://" .$_SERVER['SERVER_NAME']. $this->url('people/profile', ['id' => $usr_id]); ?>">
        <img title="<?php echo $this->displayName($user); ?>" alt="<?php echo $this->displayName($user); ?>" src="<?php echo $protocol. "://" .$_SERVER['SERVER_NAME']. $this->url('process-image', array('path' => $this->pathManager()->buildUserRoutePath($usr_id, \DocumentManager\Model\ResourceType::ICON, $usr_icon))); ?>" style="height:32px;width:32px;" />
    </a>
<?php endif; ?>
