<h3 style="text-decoration: underline;">Contact</h3>
<?php if (count($data) > 0): ?>
    <table>
        <?php foreach ($data as $d): ?>
            <tr>
                <td style="width: 130px;">
                    <?php echo $d['type']; ?>
                </td>
                <td>
                    <?php echo $d['value']; ?>
                </td>
            </tr>
        <?php endforeach; ?>
    </table>
<?php else: ?>
    <i><?php echo $this->translate('(There is no contact)'); ?></i>
<?php endif; ?>
