<?php if(count($messages)>0):?>
<table>
    <thead>
        <tr>
            <th>Subject </th>
            <th>Body</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($messages as $msg):?>
        <tr>
            <td><?php echo $msg['msg_subject']; ?></td>
            <td><?php echo $msg['msg_body']; ?></td>
        </tr>
        <?php endforeach;?>
    </tbody>
</table>
<?php endif; ?>
