<?php if (count($flashMessages) > 0): ?>
    <?php foreach ($flashMessages as $msg): ?>
        <span style="font-style: italic;">  <?php echo $msg; ?></span><br />
    <?php endforeach; ?>
<?php endif; ?>
        <h2>Inbox</h2>
<?php if (count($paginator) > 0): ?>
    <ul>
        <?php foreach ($paginator as $message): ?>
            <li> <a href="<?php echo $this->url('message/action-id', array('action' => 'view', 'id' => $message->msg_id)) ?>" style="font-weight: <?php echo  $message->msg2_isRead==0?'bold':'normal'?>"><?php echo $message->msg_subject; ?></a></li>
        <?php endforeach; ?>
    </ul>

<?php else: ?>
    <p>There are no message to show.</p>
<?php endif; ?>
    <h2>Sent Items</h2>

<?php if (count($sentMessages) > 0): ?>
    <ul>
        <?php foreach ($sentMessages as $item): ?>
            <li> <a href="<?php echo $this->url('message/action-id', array('action' => 'sentItem', 'id' => $item->msg_id)) ?>"><?php echo $item->msg_subject; ?></a></li>
        <?php endforeach; ?>
    </ul>

<?php else: ?>
    <p>There are no message to show.</p>
<?php endif; ?>