<?php if (count($this->errors) > 0): ?>
    <ul>
        <?php foreach ($this->errors as $err): ?>
            <li><?php echo $err; ?></li>
        <?php endforeach; ?>
    </ul>
<?php endif; ?>
<?php echo $this->form()->openTag($this->form); ?>
<?php
echo $this->formCollection($this->form);
?>
<div>
    <input type="submit" value="<?php echo $this->translate('Send'); ?>" name="send">
    <input type="submit" value="<?php echo $this->translate('Cancel'); ?>" name="cancel">
</div>
<?php echo $this->form()->closeTag(); ?>