<p><?php echo sprintf($this->translate('THIS IS BEING SENT FROM AN UNMONITORED MAILBOX. PLEASE DO
    NOT REPLY TO THIS EMAIL. IF YOU HAVE QUESTIONS, PLEASE
    CONTACT %shelp@linspira.com%s.'), '<a href="mailto:help@linspira.com">', '</a>'); ?></p>

<p><?php echo sprintf($this->translate('Dear %s'), $user->getFullName()); ?>,</p>


<p><?php echo sprintf($this->translate('You have added a new email address on %sLinspira.com%s. Pleas follow this link to confirm it.'), '<a href="http://linspira.com">', '</a>'); ?>
    <a href="<?php echo $this->url('people/confirm-email', array('email' => $email), array('force_canonical' => true)); ?>"><?php echo $this->url('people/confirm-email', array('email' => $email), array('force_canonical' => true)); ?></a>
</p>
<p>
    <?php echo $this->translate("If your browser doesn't open when you click the link, please
    copy and paste the link into the address bar on your browser."); ?></p>

<p>
    <?php echo $this->translate('**Help'); ?><br />
    <?php echo sprintf($this->translate('If you have any questions, contact one of our Customer
    Service associates at %shelp@linspira.com%s.'), '<a href="mailto:help@linspira.com">', '</a>'); ?></p>
<p>
    <?php echo $this->translate('Sincerely,'); ?>
</p>
<p>
    <?php echo sprintf($this->translate('Customer Service at %sLinspira.com%s [Tokyo, Japan]'), '<a href="http://linspira.com">', '</a>'); ?><br />
    <?php echo sprintf($this->translate('Sent to: %s'), $user->usr_email); ?>
</p>