<?php echo $this->listErrors($this->context->errors);       ?>
<a href="<?php echo $this->url('people/action-id', array('action' => 'edit','id'=>$userId)); ?>"><?php echo $this->translate('Go back to Edit Profile'); ?></a>
<?php if (isset($this->success) && $this->success == true): ?>
    <p>A verification email has been sent. Please confirm your email.</p>
<?php else: ?>
    <?php echo $this->form()->OpenTag($form); ?>
    <?php echo $this->formCollection($form); ?>
    <input type="submit" name="submit" value="<?php echo $this->translate('Add'); ?>" />
    <?php echo $this->form()->closeTag($form); ?> 
<?php endif; ?>