<p><?php echo sprintf($this->translate('THIS IS BEING SENT FROM AN UNMONITORED MAILBOX. PLEASE DO
    NOT REPLY TO THIS EMAIL. IF YOU HAVE QUESTIONS, PLEASE
    CONTACT %shelp@linspira.com%s.'), '<a href="mailto:help@linspira.com">', '</a>'); ?></p>

<p><?php echo sprintf($this->translate('Dear Admin Team')); ?>,</p>


<p>
    <?php echo sprintf($this->translate("There is a report violation of a project:  %s %s %s."),'<blockquote>',$project->proj_title,'</blockquote>');?></p>
<p><?php echo $this->translate('Reason: ');?><blockquote><?php echo $report->vp_comments;?></blockquote> </p>
<p><?php echo $this->translate("The reporting user is:");?> <?php echo $reporter->displayName(); ?></p>
<p><?php echo $this->translate("The owner of the project is:");?> <?php echo $this->displayName($owner); ?></p>

<p>
    <?php echo $this->translate('**Help'); ?><br />
    <?php echo sprintf($this->translate('If you have any questions, contact one of our Customer
    Service associates at %shelp@linspira.com%s.'), '<a href="mailto:help@linspira.com">', '</a>'); ?></p>
<p>
    <?php echo $this->translate('Sincerely,'); ?>
</p>
<p>
    <?php echo sprintf($this->translate('Customer Service at %sLinspira.com%s [Tokyo, Japan]'), '<a href="http://linspira.com">', '</a>'); ?><br />


