<?php if (count($paginator) > 0): ?>
    <?php foreach ($paginator as $idea): ?>
        <div class="box_idea">
            <div class="subject">
                <H2 class="ttl_idea">
                    <a style="text-decoration: none;" href="<?php echo $this->url('idea/action-id', array('action' => 'view', 'id' => $idea->idea_id)) ?>">
                        <?php echo $this->ideaHelper()->getIcon($idea); ?>
                        <?php echo $idea->idea_title; ?>
                        <?php
                        if ($idea->cat_text != "") {
                            echo " (" . $idea->cat_text . ")";
                        }
                        ?>
                    </a>
                </H2>

                <div class="good_idea">
                    <?php echo $this->ideaHelper()->followButton((object)$idea); ?>
                </div>

                <BR class="clear">
            </div>
            <div class="box1">
                <DL>
                    <DT>
                    <div style="display: inline-block;float: left;">
                        <?php echo $this->usrHelper()->getIcon($idea); ?> 
                    </div>
                    <div style="display: inline-block;padding-top: 7px;">
                        <?php echo $this->displayName($idea); ?>
                        <SPAN class="time" style="display: inline-block;">
                            posted at <?php echo $idea->idea_timeStamp; ?>
                        </SPAN>
                        <BR>
                        <?php 
                            $postedDateTime = strtotime($idea->idea_timeStamp);
                            $modifiedDateTime = strtotime($idea->idea_lastModified);
                            // Check if posted date and modified date are not the same
                            if ($postedDateTime != $modifiedDateTime) {
                        ?>
                        <SPAN class="time" style="display: inline-block;margin-left: 41px;">
                            <?php echo 'modified at '.$idea->idea_lastModified; ?>
                        </SPAN>
                        <?php } ?>
                    </div>
                    </DT>
                    <DD>
                        <?php $youtube = $this->youtube($idea->idea_attachment); ?>
                        <?php if ($youtube): ?>
                            <div style="display:inline-block;float: left;">
                                <?php echo $youtube; ?>
                            </div>
                        <?php else: ?>
                            <img src="<?php echo $this->basePath() ?>/images/img_idea.png" height="210" width="340"><!-- //TODO: this image should be $idea->idea_img (if no image and attachment is not empty, then this should be youtube video.)-->
                        <?php endif; ?>
                        <div class="idea_box">
                            <P><?php echo $idea->idea_descript; ?></P>
                            <!-- UL>
                                <LI>...</LI>
                                <LI>...</LI>
                            </UL-->
                        </div>
                        <BR class="clear">
                    </DD>
                </DL>
            </div>
        </div>
    <?php endforeach; ?>   
<?php else: ?>
    <P>You have not followed any ideas yet.</P>
<?php endif; ?>
