<?php
use DocumentManager\Model\ResourceType as Resource;
?>
<table>
    <tr>
        <td><?php echo $this->translate('Title'); ?>
        </td>
        <td><?php echo $this->idea['idea_title']; ?>
        </td>
    </tr>
    <tr>
        <td><?php echo $this->translate('Icon'); ?>
        </td>
        <td>
            <?php if ($this->idea['idea_img']!==""): ?>
                <img src="<?php echo $this->url('process-tmpimage', array('path' => $this->pathManager()->buildTmpPath(Resource::IDEA_RESOURCE, $this->idea['idea_img']))); ?>" />
            <?php endif; ?>
        </td>
    </tr>
    <tr>
        <td><?php echo $this->translate('Category');
            ?>
        </td>
        <td>
            <?php if ($this->idea['idea_categoryID'] != ""): ?>
                <?php echo $this->categoryTable->getById($this->idea['idea_categoryID'])->cat_text; ?>
            <?php endif; ?>
        </td>
    </tr>
    <tr>
        <td><?php echo $this->translate('Description'); ?>
        </td>
        <td><?php echo $this->idea['idea_descript']; ?>
        </td>
    </tr>
    <tr>
        <td><?php echo $this->translate('Presentation'); ?>
        </td>
        <td><?php echo $this->idea['idea_attachment']; ?>
        </td>
    </tr>
    <tr>
        <td><?php echo $this->translate('Referenced Ideas'); ?>
        </td>
        <td>
            <?php if (count($this->ideaRef) > 0): ?>
                <ul>
                    <?php foreach ($this->ideaRef as $ref): ?>
                        <li><?php echo $ref->idea_title; ?></li>
                    <?php endforeach; ?>
                </ul>

            <?php endif; ?>
        </td>
    </tr>
</table>
<br /><br />
<?php echo $this->form()->openTag($this->form); ?>
<?php
echo $this->formCollection($this->form);
?>
<?php echo $this->form()->closeTag(); ?>

