<?php if (isset($this->notFound)): ?>
    <?php echo $this->listErrors($this->context->errors); ?>
<?php else: ?>
    <?php if (count($evolutionList) > 0): ?>
        <ul>
            <?php foreach ($evolutionList as $idea): ?>
                <li><?php echo str_repeat('-', $idea['idea_nodeDepth']); ?> <a href="<?php echo $this->url('idea/action-id', array('action' => 'view', 'id' => $idea['idea_id'])); ?>"><?php echo $idea['idea_title']; ?></a> 
                    <a style="font-style: italic;color: green;" href="<?php echo $this->url('idea/action', array('action' => 'new'), array('query' => array('id' => $idea['idea_id']))); ?>"><?php echo $this->translate('Evolve this idea'); ?></a>
                </li>
            <?php endforeach; ?>
        </ul>
    <?php endif; ?>
<?php endif; ?>

