<?php if (isset($this->notFound)): ?>
    <?php echo $this->listErrors($this->context->errors); ?>
<?php else: ?>
    <div class="box_idea">
        <div class="subject">
            <H2 class="ttl_idea">
                <img src="<?php echo $this->url('process-image', array('path' => $this->pathManager()->buildIdeaRoutePath($this->idea->idea_id, \DocumentManager\Model\ResourceType::ICON, $this->idea->idea_img))); ?>" width="32"/>
                <?php echo $this->translate('Evolution of'); ?> <?php echo $this->idea->idea_title; ?>
                <?php if ($this->idea->idea_categoryID != 0): ?>
                    <?php echo " (" . $this->categoryTable->getById($this->idea->idea_categoryID)->cat_text . ")"; ?>
                <?php endif; ?>
            </H2>

            <BR class="clear">
        </div>
        <div class="box1" style="position: relative;">

            <?php if (count($evolutionList) > 0): ?>
                <?php $i = 1; ?>
                <?php foreach ($evolutionList as $idea): ?>
                    <div class="evolution_item<?php echo ($idea['idea_id'] == $this->idea->idea_id) ? ' current' : ''; ?>">
                        <div class="idea_side">
                            <div>
                                <a class="idea" href="<?php echo $this->url('idea/action-id', array('action' => 'view', 'id' => $idea['idea_id'])); ?>">
                                    <img src="<?php echo $this->url('process-image', array('path' => $this->pathManager()->buildIdeaRoutePath($idea['idea_id'], \DocumentManager\Model\ResourceType::ICON, $idea['idea_img']))); ?>" width="32"/>
                                </a>
                                <div class="idea_title">
                                    <a class="idea" href="<?php echo $this->url('idea/action-id', array('action' => 'view', 'id' => $idea['idea_id'])); ?>">
                                        <?php echo $idea['idea_title']; ?> 
                                    </a>
                                    <br />
                                    by <a class="idea" href="<?php echo $this->url('people/profile', array('id' => $idea['usr_id'])); ?>"><?php echo $this->displayName($idea); ?><a/>
                                </div>
                            </div>
                        </div>
                        <div class="reference_side">
                            <H2><?php echo $this->translate("Reference"); ?></H2>
                            <?php echo $this->ideaHelper()->getReference($idea['idea_id']); ?>
                        </div>

                    </div>
                    <?php if ($i < count($evolutionList)): ?>
                        <div class="down_evolution">
                        </div>
                    <?php endif; ?>
                    <?php $i++; ?>
                <?php endforeach; ?>

            <?php endif; ?>
        </div>
    </div>
<?php endif; ?>

