<?php if (count($results) > 0): ?>
    <table>
        <?php foreach ($results as $rs): ?>
            <tr>
                <td>
                    <a href="<?php echo $this->url('idea/action-id',array('action'=>'view','id'=>$rs['idea_id'])) ?>"><?php echo $rs['idea_title']; ?></a>
                    
                </td>
                <td>
                     <?php $is_followed = $followIdeaTb->isUserFollowIdea($userId, $rs['idea_id']); ?>
                    <button onclick="location.href = '<?php echo $this->url('idea/action-id',array('action'=>($is_followed?"unfollow":"follow"),'id'=>$rs['idea_id'])); ?>';"><?php echo $is_followed ? "Unsubscribe" : "Subscribe"; ?></button>
                </td>
            </tr>
        <?php endforeach; ?>
    </table>
<?php endif; ?>

