<?php echo $this->listErrors($this->context->errors);?>
<?php echo $this->headLink()->appendStylesheet($this->basePath().'/extjs4/ux/form/field/BoxSelect.css');?>

<?php echo $this->filterErrors($form); ?>

<script type="text/javascript">
    LApp.formData =<?php echo json_encode($form->getValues()); ?>;
<?php if (isset($parent)): ?>
        LApp.parent = <?php echo $parent->idea_id; ?>;
<?php endif; ?>
</script>

<div class="box_idea">
    <H2 class="ttl_idea">
        <?php if (isset($parent)): ?>
            Evolve <?php echo $parent->idea_title; ?> ( <?php echo $category->cat_text;?> )
        <?php else: ?>
            Post a new Idea
        <?php endif; ?>

    </H2><BR class="clear">
    <div class="box1" id="idea-management-new-panel"></div>
</div>