<?php if (isset($success)): ?>
    <?php echo $this->translate('The violaiton is successfully reported.'); ?>
<?php else: ?>
    <?php echo sprintf($this->translate('You are about to report viloation of the comment: %s %s %s'), '<blockquote>',$comment,'</blockquote>'); ?>
    <?php echo $this->form()->openTag($this->form); ?>
    <?php echo $this->formElementErrors($this->form); ?>
    <?php
    echo $this->formCollection($this->form);
    ?>
    <?php echo $this->form()->closeTag(); ?>
<?php endif; ?>