<?php 
use DocumentManager\Model\ResourceType as Resource;
?>
<?php echo $this->listErrors($context->errors); ?>
<?php echo $this->listSuccess($context->success); ?>
<?php if (!isset($this->notFound)): ?>
    <div class="alert">
        <?php echo sprintf($this->translate('*Maximum upload size is %s.'), \ImageManager\Model\ImgManager::getMaxUploadMessage()); ?>
    </div>

    <?php echo $this->form()->openTag($this->form); ?>
    <table>
        <tr>
            <td><?php echo $this->translate('Title'); ?>
            </td>
            <td>
                <?php echo $this->formElement($form->get('idea_title')); ?>
            </td>
        </tr>
        <tr>
            <td><?php echo $this->translate('Icon'); ?>
            </td>
            <td>
                <img src="<?php echo $this->url('process-image', array('path' => $this->pathManager()->buildIdeaRoutePath($this->idea->idea_id,Resource::ICON,$this->idea->idea_img))); ?>" /><br />
                <?php echo $this->formElement($form->get('idea_img')); ?>
            </td>
        </tr>
        <tr>
            <td><?php echo $this->translate('Category'); ?>
            </td>
            <td><?php echo $this->formElement($form->get('idea_categoryID')); ?>
            </td>
        </tr>
        <tr>
            <td><?php echo $this->translate('Description'); ?>
            </td>
            <td><?php echo $this->formElement($form->get('idea_descript')); ?>
            </td>
        </tr>
        <tr>
            <td><?php echo $this->translate('Presentation'); ?>
            </td>
            <td>
                <?php echo $this->idea->idea_attachment; ?><br />
                <?php echo $this->formElement($form->get('idea_attachment')); ?>
            </td>
        </tr>
        <tr>
            <td><?php echo $this->translate('Referenced Ideas'); ?>
            </td>
            <td>
                <?php echo $this->formElement($form->get('reference')); ?>
            </td>
        </tr>
    </table>
    <div>
        <input type="hidden" id="MAX_FILE_SIZE" name="MAX_FILE_SIZE" value="<?php echo \ImageManager\Model\ImgManager::getMaxUploadSize(); ?>" />
        <input type="submit" value="<?php echo $this->translate('Save changes'); ?>" name="save">
        <input type="submit" value="<?php echo $this->translate('Cancel'); ?>" name="cancel">
    </div>
    <?php echo $this->form()->closeTag(); ?>
<?php endif; ?>
