<?php echo $this->headLink()->appendStylesheet($this->basePath() . '/extjs4/ux/form/field/BoxSelect.css'); ?>
<?php echo $this->filterErrors($form); ?>
<?php echo $this->listErrors($this->context->errors);?>

<script type="text/javascript">
    LApp.ideaId = <?php echo $idea->idea_id;?>;
    LApp.formData =<?php echo json_encode($form->getValues()); ?>;
    LApp.imageSrc = "<?php echo $this->url('process-image', array('path' => $this->pathManager()->buildIdeaRoutePath($idea->idea_id, \DocumentManager\Model\ResourceType::ICON, $idea->idea_img))); ?>";
    LApp.ideaStoreURL = "<?php echo $this->url('idea/api', array('action' => 'getIdeaRef'), array('query' => array('id' => $idea->idea_id))); ?>";
    LApp.ideaProjectStoreURL = "<?php echo $this->url('idea/api', array('action' => 'getProject'), array('query' => array('id' => $idea->idea_id))); ?>";
<?php if ($parent !== false): ?>
        LApp.parent = <?php echo $parent->idea_id; ?>;
<?php endif; ?>
<?php if ($child !== false): ?>
        LApp.child = <?php echo $child->idea_id; ?>;
<?php endif; ?>
</script>

<div id="idea-management-update-panel"></div>