<script type="text/javascript">
    LApp.ideaMgtID = <?php echo $idea->idea_id; ?>;    
</script>
<?php if (isset($this->notFound)): ?>
    <?php echo $this->listErrors($this->context->errors); ?>
<?php else: ?>
    <!-- box1 -->
    <div class="box_idea">
        <div class="subject">
            <H2 class="ttl_idea">
                <?php echo $this->ideaHelper()->getIcon($idea); ?>
                <?php
                echo $this->idea->idea_title;
                if ($this->idea->idea_categoryID != 0) {
                    echo " (" . $this->categoryTable->getById($this->idea->idea_categoryID)->cat_text . ")";
                }
                ?></H2>
            <div class="good_idea" id="foUnfoIdea">
                <?php echo $this->ideaHelper()->followButton($this->idea); ?>
            </div>
            <BR class="clear">
        </div>
        <div class="box1" style="position: relative;">
            <DL>
                <DT>
                <div style="display: inline-block;float: left;">
                    <?php echo $this->usrHelper()->getIcon($originator); ?> 
                </div>
                <div style="display: inline-block;padding-top: 7px;">
                    <?php echo $this->displayName($originator); ?>
                    <SPAN class="time" style="display: inline-block;">
                        posted at <?php echo $idea->idea_timeStamp; ?>
                    </SPAN>
                    <BR>
                    <?php 
                        $postedDateTime = strtotime($idea->idea_timeStamp);
                        $modifiedDateTime = strtotime($idea->idea_lastModified);
                        // Check if posted date and modified date are not the same
                        if ($postedDateTime != $modifiedDateTime) {
                    ?>
                    <SPAN class="time" style="display: inline-block;margin-left: 41px;">
                        <?php echo 'modified at '.$idea->idea_lastModified; ?>
                    </SPAN>
                    <?php } ?>
                </div>
                <!--MENU-->
                <div class="menu" style="position: absolute;right: 5px;">
                    <!--<H3><img class="idea-menu" style="cursor: pointer;" src="<?php echo $this->basePath(); ?>/images/icn_down.png" height="17" width="24"></H3>-->
                    <div id='idea_menu' style="position: absolute;right: 5px;top: 5px;">
                        <?php echo $this->ideaHelper()->buildMenu($idea, $originator, $categoryTable); ?>
                    </div>
                </div>
                <!--END OF MENU-->
                </DT>
                <DD>
                    <?php $youtube = $this->youtube($idea->idea_attachment); ?>
                    <?php if ($youtube): ?>
                        <div style="display:inline-block;float: left;">
                            <?php echo $youtube; ?>
                        </div>
                    <?php else: ?>
                        <img src="<?php echo $this->basePath() ?>/images/img_idea.png" height="210" width="340">
                    <?php endif; ?>
                    <div id="ideaDesc" class="idea_box">
                        <P><?php echo $this->idea->idea_descript; ?></P>
                    </div>
                </DD>
            </DL>

        </div>

        <div class="clear"></div>
        <div id="idea-management-view-tab" style="margin-top: 10px;">
        </div>
    </div>
    <script type="text/javascript">
        //var ideaComments = document.getElementsByClassName("body").innerHTML();
        /*setTimeout(function(){
            var elements = document.getElementsByClassName('body');
            console.log(elements.innerHTML);
        }, 1000);*/
        
        /*var everythingLoaded = setInterval(function() {
          if (/loaded|complete/.test(document.readyState)) {
            clearInterval(everythingLoaded);
            //init(); // this is the function that gets called when everything is loaded
            console.log('all is loaded!');
            var elements = document.getElementsByClassName('body');
            console.log(elements.innerHTML);
          }
        }, 15000);*/
        
      

        
        //for(var x=0; x < elements.length; x++){
           //elements[x].innerHTML = response;
         //  anchorInsertAttr(elements[x].innerHTML,'rel="nofollow"');
           //console.log(elements[x].innerHTML);
        //}
        //console.log(ideaComments);
        //anchorInsertAttr(ideaComments,'rel="nofollow"');
        //document.write('Current User: '+ LApp.user.id);
    </script>
    <?php //echo 'Hi there! -'. $dataz['email']; ?>
    <?php //echo '<br> User ID! '. $dataz['user_id']; ?>
    <br>
    <?php //echo '<br> User Sessionzz! '. print_r($dataz['user_sessionid']); 
    //echo "<br><br><br>";
    /*foreach($dataz['user_sessionid'] as $key => $val):
        if($key == "sess_id"):
            echo $val."<br>";
        endif;
    endforeach;*/
    //echo 'User IP: '.$userip.'<br>';
    
    //print_r($sessid);
    echo "<br><br>";
    print_r($sessmgr);


    ?>

<?php endif; ?>