<?php
$this->inlineScript()->captureStart();
?>
        LApp.projectMenu = {
         <?php if($isOwner):?>
   
            update:{
                url:"<?php echo $this->url('project/action-id', array('action' => 'edit', 'id' => $project->proj_id)); ?>",
            }
            ,
     close:{
                url:"<?php echo $this->url('project/action-id', array('action' => 'close', 'id' => $project->proj_id)); ?>",
            }
    ,
     remove:{
                url:"<?php echo $this->url('project/action-id', array('action' => 'remove', 'id' => $project->proj_id)); ?>",
            }
    
    <?php else:?>
    <?php if(!$MemberTable->hasJoined($this->laIdentity()->usr_id,$project->proj_id)):?>
           
     join:{
                url:"<?php echo $this->url('project/action-id', array('action' => 'join', 'id' => $project->proj_id)); ?>",
                imo:"<?php echo $membershipStatus; ?>"
            },
    <?php endif;?>
     report:{
                url:"<?php echo $this->url('project/action-id', array('action' => 'report', 'id' => $project->proj_id)); ?>",
            }
    <?php endif;?>
 
           
    };
Ext.require('envitz.view.ProjectMenu');
    Ext.onReady(function(){
       
            new Ext.create('envitz.view.ProjectMenu', {
            proj_id:<?php echo $project->proj_id?>,
            proj_progress:<?php echo $project->proj_progress?>,
            projectId:<?php echo $project->proj_id?>,
            reportAlert:'<?php echo $this->translate("Please supply reason to report violation on the following project.");?>',
            hideAlert:"<?php echo $this->translate("Are you sure that you want to remove the following project?");?>",
            hideWarning:"<CENTER style='color:red'>---<?php echo $this->translate('WARNING');?>---</CENTER><div style='color:red;width:330px;'><?php echo $this->translate('The project will be permanently inaccessible from you and other users, but the data will retain on our database.');?></div>",
            projectInformation:"Project:<SPAN style='display:inline-block;margin-left:20px;'><?php echo $project->proj_title; ?></SPAN>",
            projectCreator:'<div style="margin-left:60px;"><?php echo $this->displayName($user); ?></a><SPAN class="time"> started at <?php echo $project->proj_timeStamp; ?></SPAN></div>',
            renderTo: 'project_menu'
    
        });
       
    });
<?php
$this->inlineScript()->captureEnd();
?>
