<?php

/**
 * Configuration file generated by ZFTool
 * The previous configuration file is stored in application.config.old
 *
 * @see https://github.com/zendframework/ZFTool
 */
$env = getenv('APPLICATION_ENV') ?: 'production';

$modules = array(
    'Application',
    'Users',
    'Feeder',
    'People',
    'LAhelp',
    'SearchEngine',
    'Message',
    'IdeaManagement',
    'ProjectManagement',
    'ErrorManager',
    'DocumentManager', //2014MAR - merged ImageManager with DocMgr...
    'LangManagement',
    'MenuManager',
    'Common',
);

if ($env == 'development') {
    $modules[] = 'ZendDeveloperTools';
    $modules[] = 'BjyProfiler';
}


return array(
    'modules' => $modules,
    'module_listener_options' => array(
        'config_glob_paths' => array(
            sprintf('config/autoload/{,*.}{global,%s,local}.php', $env)
        ),
        'config_cache_enabled' => ($env == 'production'),
        'config_cache_key' => 'app_config',
        'module_map_cache_enabled' => ($env == 'production'),
        'module_map_cache_key' => 'module_map',
        'cache_dir' => 'data/config/',
        'check_dependencies' => ($env != 'production'),
        'module_paths' => array(
            './module',
            './vendor'
        ),
        'config_glob_paths' => array('config/autoload/{,*.}{global,local}.php')
    )
);
