<?php echo $this->doctype(); ?>

<html lang="en">
  <head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

    <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

    <!-- Le styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
                    ->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
                    ->prependStylesheet($this->basePath() . '/css/style.css')
                    ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

    <!-- Scripts -->
    <?php echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                                  ->prependFile($this->basePath() . '/js/jquery-1.7.2.min.js') ?>

  </head>

  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">

            <SPAN class="icon-bar"></SPAN>
            <SPAN class="icon-bar"></SPAN>
            <SPAN class="icon-bar"></SPAN>
          </a>
          <a class="brand" href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Skeleton Application') ?></a>
          <div class="nav-collapse">
            <UL class="nav">
              <LI class="active"><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a></LI>
            </UL>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">

      <?php echo $this->content; ?>

      <HR>

      <FOOTER>
        <P>&copy; CopyRight 2012 &mdash; <?php echo(date("Y")); ?> by LinkAide.com <!-- Designed & written by Richie Bartlett, Jr. --><BR>
		<?php echo $this->translate('All rights reserved.') ?></P>
      </FOOTER>

    </div> <!-- /container -->

  <?php echo $this->inlineScript() ?>
  </body>
</html>
