<?php echo $this->doctype(); ?>

<html xmlns="http://www.w3.org/1999/xhtml" lang="jp">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <meta name="Content-Language" content="english" />
        <meta http-equiv="CACHE-CONTROL" content="NO-CACHE" />
        <meta http-equiv="PRAGMA" content="NO-CACHE" />
        <meta http-equiv="EXPIRES" content="Sun, 01 Jul 2012 00:00:01 GMT" />
        <meta name="DC.creator" content="Richie Bartlett Jr. - http://www.RichieBartlett.com/" />
        <meta name="DC.language" content="en" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta http-equiv="imagetoolbar" content="no" />
        <!-- meta http-equiv="X-UA-Compatible" content="IE=EmulateIE8" -->
        <meta name="copyright" content="Copyright <?php echo(date("Y")); ?>" />
        <meta name="keywords" content="Keywords here" />
        <meta name="description" content="LinkAide - Where IDEAs evolve!" />
        <meta name="Author" content="Richie Bartlett" />
        <meta name="revisit-after" content="30 days" />
        <meta name="distribution" content="global" />
        <meta name="rating" content="general" />
        <meta name="robots" content="index, follow" /> <!-- (Robot commands: All, None, Index, No Index, Follow, No Follow) -->
        <meta name="GOOGLEBOT" content="NOARCHIVE" />
        <meta charset="utf-8" />
        <meta http-equiv="content-script-type" content="text/javascript" />
        <meta http-equiv="content-style-type" content="text/css" />

        <link rel="shortcut icon" href="/favicon.ico" type="/image/ico" />
        <link rel="icon" href="/favicon.ico" type="image/ico" />
        <?php echo $this->headTitle('LinkAide.com: ' . $this->translate('Core ProtoType'))->setSeparator(' - ')->setAutoEscape(false); ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0'); ?>

        <!-- Le styles -->
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
                ->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
                ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
                ->prependStylesheet($this->basePath() . '/css/style.css');
        ?>
        <?php echo $this->headStyle(); ?>
        <link rel="stylesheet" type="text/css" href="<?php echo $this->basePath(); ?>/css/lang-jp.css" />
        <link rel="stylesheet" type="text/css" href="<?php echo $this->basePath(); ?>/css/<?php echo ($this->laIdentity() ? "feed" : "index"); ?>.css" />
        <script type="text/javascript">
            var LApp = {};
            LApp.basePath = "<?php echo $this->basePath(); ?>";
            LApp.messages = {};
            LApp.t = function(key) {
                if (this.messages[key]) {
                    return this.messages[key];
                } else {
                    return key;
                }
            };
        </script>

        <script src="<?php echo $this->basePath(); ?>/extjs4/ext-all-dev.js"></script>
        <link rel="stylesheet" href="<?php echo $this->basePath(); ?>/extjs4/packages/ext-theme-gray/build/resources/ext-theme-gray-all.css" />
        <script src="<?php echo $this->basePath(); ?>/js/drawColor.HSB.js"></script>
        <script src="<?php echo $this->basePath(); ?>/js/string.prototypes.js"></script>
        <script src="<?php echo $this->basePath(); ?>/js/baseIncludes.js"></script>
    </head>
    <body>
        <div class="frm">
            <div id="headerArea">
                <div id="logo"><a href="/" style="border:0px;"><img src="<?php echo $this->basePath(); ?>/images/logo.png" width="178" height="37"  alt="LinkAide"/></a></div>
                <?php
                //Test if the User is connected
                if (!$this->laIdentity()) {
                    // display the login form
                    echo $this->laLoginWidget();
                } else {
                    ?>
                    <div id="loginArea">
                        <div id="signOut">
                            <form action=""><input type="button" value="sign out" onclick="javascript: parent.location = '<?php echo $this->url('user', array('action' => 'logout')); ?>'"></form>
                        </div>
                    </div>
                <?php } ?>
                <BR class="clear" />
            </div>

            <div class="topIndex">
                <?php if ($this->laIdentity()) { ?>
                    <!-- feed top -->
                    <div id="feedTop">
                        <div class="profile">
                            <img src="/images/photo001.png" width="36" height="36" title="<?php echo $this->laIdentity()->usr_username; ?>" />
                            <SPAN><?php echo \Users\Model\DbEntity\User::getDisplayName((array) $this->laIdentity()); ?></SPAN>
                        </div>
                        <div class="person">
                            <div class="left input02">
                                <form id="search" name="search" method="get" action="/find">
                                    <LABEL>
                                        <input type="text" class="none" value="" placeholder="find people/ideas/projects/messages" name="keyword">
                                    </LABEL><input type="submit" name="submit" class="search right">
                                </form>
                            </div>
                            <div class="right">
                                <a style="border: none;" href="<?php echo $this->url('user', array('action' => 'settings')); ?>"><img src="/images/configGear.png"></a>
                                <a style="border: none;" href="<?php echo $this->url('help'); ?>"><img src="/images/questionMark.png"></a>
                            </div>
                        </div>
                        <BR class="clear" />
                    </div>
                    <!-- //feed top -->
                    <div id="feed" class="clearfix">
                        <div class="feed1">
                            <?php echo $this->laMenuWidget(); ?>
                        </div>
                    <?php } ?>



                    <div class="feed2">
                        <div class="box">
                            <?php echo $this->content; ?>
                        </div>
                    </div>


                    <?php if ($this->laIdentity()) { ?>



                    </div><!-- //feed -->
                <?php } ?>

            </div><!-- //topIndex -->

            <div style="clear: both"></div>

            <FOOTER>
                <div id="footerArea">

                    <?php if (!$this->laIdentity()): ?>
                        <UL class="lang">
                            <LI><a href="<?php echo $this->url('lang', array('lang' => 'en_US')); ?>" style="color:#000000"><SPAN lang="en" xml:lang="en">English</SPAN></a></LI>
                            <LI><a href="<?php echo $this->url('lang', array('lang' => 'es_ES')); ?>" style="color:#000000"><SPAN lang="es" xml:lang="es">Español</SPAN></a></LI>
                            <LI><a href="<?php echo $this->url('lang', array('lang' => 'zh_CN')); ?>" style="color:#000000"><SPAN lang="zh" xml:lang="zh">中文(简化)</SPAN></a></LI>
                            <LI><a href="<?php echo $this->url('lang', array('lang' => 'fr_FR')); ?>" style="color:#000000"><SPAN lang="fr" xml:lang="fr">Français</SPAN></a></LI>
                            <LI><a href="<?php echo $this->url('lang', array('lang' => 'ja_JP')); ?>" style="color:#000000"><SPAN lang="ja" xml:lang="ja">日本語</SPAN></a></LI>
                        </UL>
                    <?php endif ?>
                    <UL class="foot">
                        <LI><a href="/" style="color:#000000">Link Aide</a></LI>
                        <LI><a href="/legal/privacy" style="color:#000000">Privacy</a></LI>
                        <LI><a href="/legal/tos.html" style="color:#000000">Terms</a></LI>
                        <LI><a href="/help" style="color:#000000">Help</a></LI>
                    </UL>

                    <!--
                                      <P style="color:#DDDDDD">(Need to update links and shortcuts in this FOOTER...)<BR>
                    
                                              <table class="LAfootTable">
                                                        <tr>
                                                                <td>Getting Started:
                                                                          <UL>
                                                                                  <LI>Create a free account</LI>
                                                                                  <LI>Search idea or project</LI>
                                                                          </UL>
                                                                </td>
                                                                <td>Create:
                                                                          <UL>
                                                                                  <LI>Post your Idea</LI>
                                                                                  <LI>Start your Project</LI>
                                                                                  <LI>Create your team</LI>
                                                                          </UL>
                                                                </td>
                                                                <td>Support:
                                                                          <UL>
                                                                                  <LI>Forum</LI>
                                                                                  <LI>FAQ</LI>
                                                                                  <LI>Contact Us</LI>
                                                                          </UL>
                                                                </td>
                                                                <td>Company:
                                                                          <UL>
                                                                                  <LI>About LinkAide</LI>
                                                                                  <LI>Founders</LI>
                                                                                  <LI>Investors</LI>
                                                                                  <LI>Partners</LI>
                                                                                  <LI>Press Releases</LI>
                                                                                  <LI>Legal</LI>
                                                                          </UL>
                                                                </td>
                                                                <td>Social:
                                                                          <UL>
                                                                                  <LI>Facebook</LI>
                                                                                  <LI>LinkedIn</LI>
                                                                                  <LI>Twitter</LI>
                                                                                  <LI>Vimeo</LI>
                                                                                  <LI>Google+</LI>
                                                                          </UL>
                                                                </td>
                                                        </tr>
                                              </table>
                                      </P>
                    
                    
                            <HR width="100%">
                    
                    -->	
                    <BR class="clear" />
                    <div class="copyright">LINK AIDE &copy; 2012 &mdash; <?php echo(date("Y")); ?>
                        <?php echo $this->translate('All rights reserved.'); ?>
                    </div><!-- Designed & written by Richie Bartlett, Jr. -->
                </div>
            </FOOTER>
            <?php echo $this->inlineScript(); ?>
    </body>
</html>
