<a href="<?php echo $this->url('people/action-id', array('action' => 'edit', 'id' => $this->context->userId)); ?>">Back</a>
<?php if (count($this->errors) > 0): ?>
    <ul>
        <?php foreach ($this->errors as $err): ?>
            <li><?php echo $err; ?></li>
        <?php endforeach; ?>
    </ul>
<?php endif; ?>
<?php echo $this->formElementErrors($form); ?>
<?php echo $this->form()->openTag($this->form); ?>
<?php
echo $this->formCollection($this->form);
?>
<?php echo $this->form()->closeTag(); ?>
<?php if (count($skillList) > 0): ?>
    Skills:
    <ul>
        <?php foreach ($skillList as $skill): ?>
            <li>
                <?php echo $skill['stag_text']; ?>
            </li>
        <?php endforeach; ?>
    </ul>
<?php endif; ?>


