<div class="feed_box">
    <div class="subject">
        <H2>
            <?= $this->usrHelper()->getIcon($user); ?> <?= $user->displayName(); ?> has commented on the idea "<?= $idea->idea_title; ?>"
            <span class="date">
                <?= $iCom->iComm_timeStamp; ?>
            </span>
        </H2>
    </div>
    <div class="content">
        <div class="title" style="font-size: 1.2em;margin-bottom: 15px;">
            <a class="idea" href="<?= $this->url('idea/action-id',['action'=>'view','id'=>$idea->idea_id])?> "><?= $this->ideaHelper()->getIcon($idea); ?><?= $idea->idea_title; ?></a><BR>
        </div>
        
        <?= $iCom->iComm_comment; ?>
    </div>
</div>