<div class="feed_box">
    <div class="subject">
        <H2>
            <?= $this->usrHelper()->getIcon($user); ?> <?= $user->displayName(); ?> has evolved an idea "<?= $parentIdea->idea_title; ?>" to "<?= $idea->idea_title; ?>"
            <span class="date">
                <?= $idea->idea_timeStamp; ?>
            </span>
        </H2>
    </div>
    <div class="content">
        <div class="title" style="font-size: 1.2em;margin-bottom: 15px;">
            <a class="idea" href="<?= $this->url('idea/action-id',['action'=>'view','id'=>$parentIdea->idea_id])?> "><?= $this->ideaHelper()->getIcon($parentIdea); ?><?= $parentIdea->idea_title; ?></a>
            <img src="/images/arrow_right.png" />
            <a class="idea" href="<?= $this->url('idea/action-id',['action'=>'view','id'=>$idea->idea_id])?> "><?= $this->ideaHelper()->getIcon($idea); ?><?= $idea->idea_title; ?></a>
            <BR>
        </div>
        
        <?= $idea->idea_descript; ?>
    </div>
</div>