<div class="feed_box">
    <div class="subject">
        <H2>
            <?= $this->usrHelper()->getIcon($user); ?> <?= $user->displayName(); ?> has joined the project "<?= $project->proj_title; ?>"
            <span class="date">
                <?= $pMem->pMem_dateTime; ?>
            </span>
        </H2>
    </div>
    <div class="content">
        <div class="title" style="font-size: 1.2em;margin-bottom: 15px;">
            <a class="project" href="<?= $this->url('project/action-id',['action'=>'view','id'=>$project->proj_id])?> "><?= $this->projHelper()->getIcon($project); ?><?= $project->proj_title; ?></a><BR>
        </div>
        
        <?= $project->proj_title; ?>
    </div>
</div>