<div class="box" style="overflow: hidden">
    <div class="subject"><H2><?php echo $this->translate('Hot Ideas'); ?></H2></div>
    <?php if (count($hotIdeas) > 0): ?>

        <?php foreach ($hotIdeas as $idea): ?>
            <a style="text-decoration: none;" href="<?php echo $this->url('idea/action-id', array('action' => 'view', 'id' => $idea['idea_id'])); ?>">
                <div class="idea-block">
                    <?php echo $this->ideaHelper()->getIcon($idea); ?>
                    <div class="detail">
                        <div class="title"><?php echo $idea['idea_title']; ?></div>
                        <div class='by'> by <?php echo $this->displayName($idea); ?></div>
                    </div>
                </div>
            </a>
        <?php endforeach; ?>

    <?php endif; ?>
</div>
<BR class="clear">
