<!-- mainArea -->
<div id="topIndex">
	<div class="topleft">
		<div class="left"><img src="/images/top006.png" width="346" height="210" alt="" /></div>
		<div class="right txtW">
			<P>Simple 3 steps for success</P>
			<OL>
				<LI>Publish your idea</LI>
				<LI>Find people</LI>
				<LI>Work together</LI>
			</OL>
			<P class="right"><a href="/" class="txtW">&gt;&gt; learn more</a></P>
			<BR class="clear" />
		</div>
	</div>
    <div class="topright">
		<P class="txtW"><?php echo $this->translate('Join us for the Revolution!!') ?></P>
<?PHP
	// Join Widget:
	echo $this->laJoinWidget();
?>
</div>
<!-- //mainArea -->
