<style type="text/css">
.font001 { font-family: ヒラギノ角ゴ Pro W3, Hiragino Kaku Gothic Pro, メイリオ, Meiryo, Osaka, ＭＳ Ｐゴシック, MS PGothic, sans-serif; }
.input001 {
	border:1px solid #d0d0d0;
	border-radius:16px;
	-webkit-border-radius:16px;
	-moz-border-radius:16px;
}
.input001::-webkit-input-placeholder{ font-style:italic; }
.input001::-moz-placeholder{ font-style:italic; }
</style>

<div class="hero-unit">
		<div style="float:right;">
			<H2><?php echo $this->translate('Join us for the Revolution!!') ?></H2>
<?PHP
$form = $this->registerForm;
$form->prepare();
$form->setAttribute('action', $this->url('zfcuser/register'));
$form->setAttribute('method', 'post');
?>

<?php echo $this->form()->openTag($form) ?>
    <DL class="zend_form">
    <?php foreach ($form as $element): ?>
        <?php if (!$element instanceof Zend\Form\Element\Button): ?>
            <DT><?php echo $this->formLabel($element) ?></DT>
        <?php endif ?>
        <?php if ($element instanceof Zend\Form\Element\Button): ?>
            <DD><?php echo $this->formButton($element) ?></DD>
        <?php elseif ($element instanceof Zend\Form\Element\Captcha): ?>
            <DD><?php echo $this->formCaptcha($element) . $this->formElementErrors($element) ?></DD>
        <?php else: ?>
            <DD><?php echo $this->formInput($element) . $this->formElementErrors($element) ?></DD>
        <?php endif ?>
    <?php endforeach ?>
    </DL>
    <?php if ($this->redirect): ?>
        <input type="hidden" name="redirect" value="<?php echo $this->escapeHtml($this->redirect) ?>" />
    <?php endif ?>
<?php echo $this->form()->closeTag() ?>

<!--
<form>
	<input type="text" id="newUsername" value="Name" style="width:200px;"><BR>
	<input type="text" id="newEmail" value="name@email.com" style="width:200x;"><BR>
	<input type="submit" class="btn btn-success" value="Sign Up" style="float:right">
</form>
-->
		</div>
    <H1><?php echo sprintf($this->translate('Welcome to Link Aide') ) ?></H1>
    <P><?php echo sprintf($this->translate('Congratulations! You are one click away from a world of <B>Ideas</B>!. <BR>Currently running on Zend Framework version %s.'), \Zend\Version\Version::VERSION) ?></P>




</div>

<div class="row">

    <div class="span4">
        <H2><?php echo $this->translate('Discover Ideas') ?></H2>
        <P><?php echo sprintf($this->translate('The community is open to your new idea!')) ?></P>
        <P><a class="btn btn-success" href="/ideas" target="_blank"><?php echo $this->translate('Begin Exploring') ?> &raquo;</a></P>
   </div>

   <div class="span4">
       <H2><?php echo $this->translate('Help &amp; Support') ?></H2>
       <P><?php echo sprintf($this->translate('If you need any help or support while developing with ZF2, you may reach us via IRC: %s#zftalk.2 on Freenode%s. We\'d love to hear any questions or feedback you may have regarding the beta releases. Alternatively, you may subscribe and post questions to the %smailing lists%s.'), '<a href="irc://irc.freenode.net/zftalk.2">', '</a>', '<a href="http://framework.zend.com/wiki/display/ZFDEV/Mailing+Lists">', '</a>') ?></P>
       <P><a class="btn btn-success" href="http://webchat.freenode.net?channels=zftalk.2" target="_blank"><?php echo $this->translate('Ping us on IRC') ?> &raquo;</a></P>
   </div>
</div>
