<?php
$this->inlineScript()->captureStart();
echo <<<JS
   document.getElementById( 'present' ).addEventListener( 'click', function () {
        var toDate=document.getElementById('toDate');
        if(this.checked){
            toDate.setAttribute("style","display:none;");
            toDate.setAttribute("value","9999-12-31");
        }else{
            toDate.setAttribute("style","display:table-cell;");
            toDate.setAttribute("value","");
        }
    }, false );

JS;
$this->inlineScript()->captureEnd();
?>

<a href="<?php echo $this->url('people/action-id', array('action' => 'edit', 'id' => $userId)); ?>">Back</a>
<?php if (count($this->errors) > 0): ?>
    <ul>
        <?php foreach ($this->errors as $err): ?>
            <li><?php echo $err; ?></li>
        <?php endforeach; ?>
    </ul>
<?php endif; ?>
<?php echo $this->form()->openTag($this->form); ?>
<?php
echo $this->formElementErrors($form);
if ($form->get('xp_toDate')->getValue() == '9999-12-31') {
    $form->get('xp_toDate')->setAttributes(array('style' => 'display:none'));
}
?>

<table style="">
    <tr>
        <td><?php echo $this->translate('Name'); ?></td>
        <td><?php echo $this->formElement($this->form->get('xp_name')); ?></td>
    </tr>
    <tr>
        <td><?php echo $this->translate('From'); ?></td>
        <td><?php echo $this->formElement($this->form->get('xp_fromDate')); ?></td>
    </tr>
    <tr>
        <td><?php echo $this->translate('To'); ?></td>
        <td><?php echo $this->formElement($this->form->get('xp_toDate')); ?> <input type="checkbox"<?php echo ($form->get('xp_toDate')->getValue() == '9999-12-31' ? ' checked' : ''); ?> name="present" id="present"/> <label style="display: inline-block" for="present">Present</label> </td>
    </tr>
    <tr>
        <td><?php echo $this->translate('Description'); ?></td>
        <td><?php echo $this->formElement($this->form->get('xp_descript')); ?></td>
    </tr>
    <tr>
        <td></td>
        <td><input type="submit" value="Save changes" /></td>
    </tr>
</table>

<?php echo $this->form()->closeTag(); ?>
