<?php

use DocumentManager\Model\ResourceType as Resource;
?>
<table>
    <tr>
        <td><?php echo $this->translate('Title'); ?>
        </td>
        <td><?php echo $this->project['proj_title']; ?>
        </td>
    </tr>
    <tr>
        <td><?php echo $this->translate('Source Idea'); ?>
        </td>
        <td><?php echo $this->ideaTable->getById($this->project['proj_srcIdea'])->idea_title; ?>
        </td>
    </tr>
    <tr>
        <td><?php echo $this->translate('Icon'); ?>
        </td>
        <td>
            <?php if ($this->project['proj_img'] !== ""): ?>
                <img src="<?php echo $this->url('process-tmpimage', array('path' => $this->pathManager()->buildTmpPath(Resource::PROJECT_RESOURCE, $this->project['proj_img']))); ?>" />
            <?php endif; ?>
        </td>
    </tr>
    <tr>
        <td><?php echo $this->translate('Description'); ?>
        </td>
        <td><?php echo $this->project['proj_descript']; ?>
        </td>
    </tr>
    <tr>
        <td><?php echo $this->translate('Members'); ?>
        </td>
        <td>
            <ul>
                <?php if (count($this->members) > 0): ?>
                    <?php foreach ($this->members as $mem): ?>
                        <li><?php echo $mem->usr_fName . ' ' . $mem->usr_lName; ?></li>
                    <?php endforeach; ?>
                <?php endif; ?>
            </ul>
        </td>
    </tr>
</table>
<br /><br />
<?php echo $this->form()->openTag($this->form); ?>
<?php
echo $this->formCollection($this->form);
?>
<?php echo $this->form()->closeTag(); ?>

