<div class="alert">
    <?php echo sprintf($this->translate('*Maximum upload size is %s.'), \ImageManager\Model\ImgManager::getMaxUploadMessage()); ?>
</div>
<?php if(isset($requester)):?>
    <?php echo sprintf($this->translate('New Member %s%s%s'),'<a target="_blank" href="'.$this->url('people/profile',array('id'=>$requester->usr_id)).'">',$requester->usr_fName,'</a>');?>
<?php endif;?>
<BR />
<?php echo $this->form()->openTag($this->form); ?>
<?php
echo $this->formCollection($this->form);
?>
<div>
    <input type="hidden" id="MAX_FILE_SIZE" name="MAX_FILE_SIZE" value="<?php echo \ImageManager\Model\ImgManager::getMaxUploadSize(); ?>" />
    <input type="submit" value="<?php echo $this->translate('Save'); ?>" name="Save">
    <input type="submit" value="<?php echo $this->translate('Cancel'); ?>" name="cancel">
</div>
<?php echo $this->form()->closeTag(); ?>