<?php echo $this->listErrors($this->context->errors);?>
<?php echo $this->headLink()->appendStylesheet($this->basePath().'/extjs4/ux/form/field/BoxSelect.css');?>
<?php $this->headStyle()->captureStart() ?>
div.proj-mem-list{display:inline-block;}
<?php $this->headStyle()->captureEnd() ?>
<script type="text/javascript">
    LApp.formData=<?php echo json_encode($form->getValues());?>;
</script>

<div class="box">
	<H2 class="ttl_idea">Start a new project</H2><BR class="clear">
	<div class="box1" id="project-management-new-panel"></div>
</div>